export const COLLECTIONS = {
  stores: "stores",
  storeSettings: "storeSettings",
  storeRules: "storeRules",
  adminUsers: "adminUsers",
  customers: "customers",
  orders: "orders",
  cards: "cards",
  inventory: "inventory",
  transactions: "transactions",
  counters: "counters",
  adminLogs: "adminLogs",
  feedback: "feedback",
  pricechartingProductsCurrent: "pricecharting_products_current",
  cardPriceSnapshots: "card_price_snapshots",
  pricechartingImportRuns: "pricecharting_import_runs",
  pricechartingDailyReports: "pricecharting_daily_reports",
  storeEvents: "storeEvents",
  storeEventSignups: "storeEventSignups",
  inventoryImportSnapshots: "inventoryImportSnapshots",
  catalogCards: "catalogCards",
  catalogOracleCards: "catalogOracleCards",
  catalogSyncState: "catalogSyncState",
  edhrecCommanderMeta: "edhrecCommanderMeta",
  edhrecSyncRuns: "edhrecSyncRuns",
  storeDecks: "storeDecks",
  cardCrosswalk: "cardCrosswalk",
  goldenCatalogImportRuns: "goldenCatalogImportRuns",
  catalogRulings: "catalogRulings",
  catalogRulingsStaging: "catalogRulingsStaging",
  catalogRulingsVersions: "catalogRulingsVersions",
  mtgKnowledgeSources: "mtgKnowledgeSources",
  mtgKnowledgeChunks: "mtgKnowledgeChunks",
  mtgKnowledgeAliases: "mtgKnowledgeAliases",
  mtgKnowledgeIngestionRuns: "mtgKnowledgeIngestionRuns",
  mtgKnowledgeEvaluations: "mtgKnowledgeEvaluations",
} as const;

export const STORE_SETTINGS_DOC = "default";
export const DEFAULT_STORE_ID = "the-game-lodge";
