/**
 * Professor + RAG architecture audit v1 — code trace from implementation.
 */
export const PROFESSOR_RAG_ARCHITECTURE_AUDIT_V1_VERSION = "phase6a1-professor-rag-architecture-audit-v1";

export const PROFESSOR_ARCHITECTURE_AUDIT = {
  professor: {
    status: "SPEC_ONLY — implementation WAIT",
    specFile: "web/src/lib/deck-synthesis/semantic-deckbuilding-professor-v1-spec.ts",
    specVersion: "semantic-deckbuilding-professor-v1-spec",
    plannedModel: "GPT-5.6 Sol",
    plannedReasoningEffort: "xhigh",
    modelConfigurable: true,
    orchestration: "Single frontier model with deterministic tool loop via Responses API (not implemented)",
    hardRule: "Professor proposes. Deterministic system disposes.",
    runtimeEntryPoints: [],
    apiRoutes: [],
    uiEntryPoints: [
      {
        file: "web/src/components/deck-build/DeckBuildApp.tsx",
        element: "Ask Professor button",
        status: "disabled",
        title: "Professor implementation WAIT",
      },
    ],
    plannedTools: [
      "searchMtgRag(query)",
      "getCard(oracleId)",
      "explainCardSemantics(oracleId)",
      "inspectCurrentDeck()",
      "getBuildDirections()",
      "findSemanticCandidates(requirements)",
      "getSemanticNeighbors(oracleId)",
      "evaluateDeck(deck)",
      "evaluateSwap(remove, add)",
      "validateCommanderLegality(deck)",
      "validateBracket(deck, bracket)",
      "inspectRoleCoverage(deck)",
    ],
    professorCallsRag: false,
    professorCallsRagNote: "searchMtgRag is planned in spec only; no runtime Professor agent exists",
    escalationContract: {
      typesFile: "web/src/lib/deck-synthesis/semantic-candidate-retrieval-v1.ts",
      functions: ["ProfessorAssistanceRequest", "buildProfessorAssistanceRequest()"],
      triggers: [
        "retrieval_abstention",
        "low_direction_confidence",
        "multiple_nearly_equal_build_directions",
        "user_manual_selection_conflicts_with_profile",
        "optimizer_local_plateau",
        "disconnected_semantic_packages_in_deck",
        "user_asks_what_am_i_building",
        "user_asks_for_advice_or_explanation",
      ],
      consumedAtRuntime: false,
    },
    legacyCopilotAlias: "web/src/lib/deck-synthesis/semantic-deckbuilding-copilot-v1-spec.ts",
  },
  mtgRag: {
    status: "IMPLEMENTED",
    featureFlag: "MTG_RAG_ENABLED=true",
    vectorStore: "Firestore findNearest on embedding field (FieldValue.vector)",
    collections: [
      "mtgKnowledgeSources",
      "mtgKnowledgeChunks",
      "mtgKnowledgeAliases",
      "mtgKnowledgeIngestionRuns",
      "mtgKnowledgeEvaluations",
    ],
    embeddingModel: "text-embedding-3-small",
    embeddingDimensions: 1536,
    ingestionVersion: "phase2-v1",
    retrievalLimit: 8,
    vectorCandidateLimit: 12,
    retrievalMethods: ["alias_exact", "vector", "embedded_clerk_glossary_fallback"],
    entryFunction: "hybridRetrieveMtgKnowledge()",
    entryFile: "web/src/lib/mtg-rag/hybrid-retrieval.ts",
    queryEmbedding: "embedQueryText() — web/src/lib/mtg-rag/embed-query.ts",
    chunkSchemaFile: "web/src/lib/mtg-rag/types.ts — MtgKnowledgeChunk",
    corpora: ["glossary", "color_identity", "commander_primer", "comprehensive_rules", "youtube_transcript"],
    authorityTiers: ["live_canonical_data", "official_rules", "curated_internal", "community_education"],
    queryIntents: [
      "inventory_lookup",
      "price_lookup",
      "card_identity_oracle",
      "rules_question",
      "terminology_question",
      "color_identity_question",
      "commander_strategy",
      "deckbuilding_education",
      "recommendation",
      "mixed",
    ],
    sourceDefinitions: "web/src/lib/mtg-rag/source-definitions.ts",
    transcriptTopics: [
      "deckbuilding101",
      "commanderdeckbuildingmath",
      "archetypesofcommander",
      "creativedeckbuilding",
      "quadrant-theory",
      "bracket4commander",
      "and others",
    ],
    ranking: "authorityTier desc, alias_exact preferred, then score",
    formatForLlm: "formatKnowledgeHitsForLlm()",
  },
  ragCallSites: {
    professor: [],
    storeClerkDeckBuild: [
      {
        file: "web/src/lib/store-inventory/commander-deck-build-service.ts",
        function: "initSession()",
        intent: "commander_strategy",
        purpose: "Strategy primer notes",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/deck-build-planner.ts",
        function: "planCommanderForDeckBuild()",
        model: "gpt-4o-mini via callOpenAiJson",
        purpose: "Commander pick + strategy summary with RAG context",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/deck-build-intent-translator.ts",
        function: "translateDeckBuildIntent()",
        model: "gpt-4o-mini",
        purpose: "Intent translation with RAG context",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/commander-deck-stages.ts",
        function: "runCommanderDeckBuildStage()",
        purpose: "RAG notes at synergy stage → session.ragNotes",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/knowledge-retrieval.ts",
        function: "retrieveKnowledgeForClerk()",
        purpose: "General clerk knowledge",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/rag-guided-inventory.ts",
        function: "searchInventoryViaRag(), extractCardNamesFromKnowledge()",
        purpose: "RAG → card names → inventory match",
      },
      {
        file: "web/src/lib/store-inventory/clerk-tools/inventory-query-reinterpret.ts",
        purpose: "Query reinterpretation with RAG",
      },
      {
        file: "web/src/lib/store-inventory/simple-clerk/simple-rules.ts",
        purpose: "Rules questions",
      },
    ],
    deckBuilderChat: {
      file: "web/src/app/api/store/[slug]/deck-builder/chat/route.ts",
      usesRag: false,
      note: "Static COMMANDER_DECK_BUILDER_GUIDE + EDHREC — no mtg-rag",
    },
    mtgKnowledgeSpecialist: {
      file: "web/src/lib/store-inventory/specialists/mtg-knowledge-specialist.ts",
      note: "Can fall back to direct model knowledge when RAG disabled",
    },
  },
  deadOrUnusedPaths: [
    {
      path: "Professor searchMtgRag tool",
      status: "SPEC_ONLY — never wired",
    },
    {
      path: "semantic-candidate-retrieval buildProfessorAssistanceRequest()",
      status: "Payload builder exists; no consumer agent",
    },
    {
      path: "deck-builder/chat route",
      status: "Live chat without RAG — parallel legacy path",
    },
    {
      path: "semantic-candidate-retrieval-v1/v1.1",
      status: "Script-only eval; not live API; separate from mtg-rag",
    },
  ],
  semanticCandidateRetrieval: {
    status: "IMPLEMENTED — deterministic, not vector RAG",
    files: [
      "web/src/lib/deck-synthesis/semantic-candidate-retrieval-v1.ts",
      "web/src/lib/deck-synthesis/semantic-candidate-retrieval-v1.1.ts",
    ],
    mechanism: "Semantic map + catalog role index + shadow index",
    usedByProfessor: false,
    usedByLiveApi: false,
    usedByScripts: "Phase 6A.1 evaluation scripts only",
  },
  buildPathV3Disposition: {
    role: "GOLD_DEV_STRATEGY_REFERENCE",
    catalog: "phase6a1-build-path-catalog-v3.json",
    pathIntents: 167,
    gateB: "WAIT",
    newRetrievalTokens: "WAIT",
  },
} as const;
