import { resolve } from "node:path";

export const MECHANICAL_SPACE_DIR = resolve(process.cwd(), "data/milestones/mechanical-space");

export const MECHANICAL_SPACE_ARTIFACTS = {
  discovery: "architecture-discovery.json",
  snapshotDir: "semantic-oracle-snapshot-v1",
  snapshotManifest: "semantic-oracle-snapshot-v1/manifest.json",
  snapshotVectors: "semantic-oracle-snapshot-v1/vectors.f32",
  snapshotIndex: "semantic-oracle-snapshot-v1/index.jsonl",
  snapshotValidation: "semantic-oracle-snapshot-v1/validation.json",
  spellbookDir: "spellbook-reference-normalization-v1",
  identityDir: "oracle-identity-mapping-v1",
  parityDir: "mechanical-graph-parity-v1",
  supervisionDir: "mechanical-supervision-v1",
  mlDir: "mechanical-feature-ml-v1",
  reconstructionDir: "mechanical-holdout-reconstruction-v1",
  candidatesDir: "mechanical-novel-candidates-v1",
  reviewsDir: "local-reviews",
  neuralDir: "oracle-neural-semantic-space-v1",
  comparisonDir: "representation-comparison-v1",
  graphEmbedDir: "mechanical-graph-embedding-v1",
  alignmentDir: "mechanical-alignment-v1",
  directionsDir: "mechanical-directions-v1",
  directionsV2Dir: "mechanical-directions-v2",
  directionsV21Dir: "mechanical-directions-v21",
  pressureKDir: "mechanical-pressure-k-v1",
  deckProfilesDir: "deck-mechanical-profiles-v1",
  deckPressureDir: "deck-pressure-v1",
  pressureKV11Dir: "mechanical-pressure-k-v1.1",
  deckPressureV11Dir: "deck-pressure-v1.1",
  pressureKV12Dir: "mechanical-pressure-k-v1.2",
  deckPressureV12Dir: "deck-pressure-v1.2",
  pressureKV13Dir: "mechanical-pressure-k-v1.3",
  deckPressureV13Dir: "deck-pressure-v1.3",
  pressureKV14Dir: "mechanical-pressure-k-v1.4",
  deckPressureV14Dir: "deck-pressure-v1.4",
  pressureKV15Dir: "mechanical-pressure-k-v1.5",
  deckPressureV15Dir: "deck-pressure-v1.5",
  directionsV22Dir: "mechanical-directions-v22",
  deckProfilesV2Dir: "deck-mechanical-profiles-v2",
  pressureKV20Dir: "mechanical-pressure-k-v2.0",
  pressureKV21Dir: "mechanical-pressure-k-v2.1",
  pressureKV22Dir: "mechanical-pressure-k-v2.2",
  pressureKV23Dir: "mechanical-pressure-k-v2.3",
  pressureKV24Dir: "mechanical-pressure-k-v2.4",
  hCalibrationAuditV1Dir: "h-calibration-audit-v1",
  compatibilityScreenV1Dir: "compatibility-screen-v1",
  pressureKV25Dir: "mechanical-pressure-k-v2.5",
  pressureKV26Dir: "mechanical-pressure-k-v2.6",
  interactionDiversityAuditV1Dir: "interaction-diversity-audit-v1",
  pressureKV27Dir: "mechanical-pressure-k-v2.7",
  deckPressureV2Dir: "deck-pressure-v2",
  hodgeDiagnosticV0Dir: "hodge-diagnostic-v0",
  hodgeDiagnosticV1Dir: "hodge-diagnostic-v1",
  corpusExpansionV1Dir: "corpus-expansion-v1",
  expansionProfilesV2Dir: "expansion-profiles-v2",
  frozenKApplicabilityAuditV1Dir: "frozen-k-applicability-audit-v1",
  pressureKV30Dir: "mechanical-pressure-k-v3.0",
  deckPressureV3Dir: "deck-pressure-v3",
  corpusExpansionV2Dir: "corpus-expansion-v2",
  corpusExpansionV2ExhaustionAuditDir: "corpus-expansion-v2/exhaustion-audit",
  corpusExpansionV2Attempt1InvalidDir: "corpus-expansion-v2/attempt-1-invalid",
  corpusExpansionV2ExhaustionAuditAttempt2Dir: "corpus-expansion-v2/exhaustion-audit-attempt-2",
  corpusExpansionV2Attempt2HoldDir: "corpus-expansion-v2/attempt-2-hold",
  corpusExpansionV2Attempt3FailedExecutionDir: "corpus-expansion-v2/attempt-3-failed-execution",
  expansionV2ProfilesV2Dir: "expansion-v2-profiles-v2",
  expansionV2D50PackageIntegrityDir: "expansion-v2-profiles-v2/d50-package-integrity-audit",
  frozenKApplicabilityAuditV2Dir: "frozen-k-applicability-audit-v2",
  deckPressureV4Dir: "deck-pressure-v4",
  generalizedCycleAuditV1Dir: "generalized-cycle-audit-v1",
  topologyDiagnosticV2Dir: "topology-diagnostic-v2",
  aggregationSensitivityAuditV1Dir: "aggregation-sensitivity-audit-v1",
  bilateralCancellationAuditV1Dir: "bilateral-cancellation-audit-v1",
  stableHostileOrderAuditV1Dir: "stable-hostile-order-audit-v1",
  orderBackboneRobustnessAuditV1Dir: "order-backbone-robustness-audit-v1",
  emergentRegionabilityAuditV1Dir: "emergent-regionability-audit-v1",
  continuousOrderGeometryAuditV1Dir: "continuous-order-geometry-audit-v1",
  mechanicalOrderInterpretationAuditV1Dir: "mechanical-order-interpretation-audit-v1",
  externalStrategicValidityAuditV1Dir: "external-strategic-validity-audit-v1",
  prospectiveStrategicValidationProtocolV1Dir: "prospective-strategic-validation-protocol-v1",
  externalGameplayValidationV1Dir: "external-gameplay-validation-v1",
  externalGameplayOutcomeAuditV1Dir: "external-gameplay-outcome-audit-v1",
  externalGameplayOutcomeAuditV2Dir: "external-gameplay-outcome-audit-v2",
  externalGameplayOutcomeAuditV3Dir: "external-gameplay-outcome-audit-v3",
  meleeStructuredSourceFeasibilityV1Dir: "melee-structured-source-feasibility-v1",
  getpairdStructuredSourceFeasibilityV1Dir: "getpaird-structured-source-feasibility-v1",
  twoTrackValidationArchitectureV1Dir: "two-track-validation-architecture-v1",
  topdeckHoldoutOutcomeValidationV1Dir: "topdeck-holdout-outcome-validation-v1",
  observedMechanismValidationV1Dir: "observed-mechanism-validation-v1",
  outcomeDerivedStrategicGeometryV1Dir: "outcome-derived-strategic-geometry-v1",
  odsgV1RepresentationArchitectureFreezeV1Dir:
    "outcome-derived-strategic-geometry-v1/representation-architecture-freeze-v1",
  odsgV1TrainingProcedureAmendmentV1Dir:
    "outcome-derived-strategic-geometry-v1/training-procedure-amendment-v1",
  odsgV1ModelSelectionPredictionFreezeV1Dir:
    "outcome-derived-strategic-geometry-v1/model-selection-prediction-freeze-v1",
  odsgV1FinalTestAdjudicationV1Dir:
    "outcome-derived-strategic-geometry-v1/final-test-adjudication-v1",
  odsgV1LineageCloseV1Dir: "outcome-derived-strategic-geometry-v1/lineage-close-v1",
  commanderMetaMatchupGeometryV1Dir: "commander-meta-matchup-geometry-v1",
  cmmgV1DevelopmentModelFreezeV1Dir: "commander-meta-matchup-geometry-v1/development-model-freeze-v1",
  cmmgV1ProspectiveTestAccumulatorV1Dir: "commander-meta-matchup-geometry-v1/prospective-test-accumulator-v1",
  commanderspellbookIntegrationAuditV1Dir: "commanderspellbook-integration-audit-v1",
  historicalCommanderMetaGeometryV1Dir: "historical-commander-meta-geometry-v1",
  commanderspellbookFullMirrorV1Dir: "commanderspellbook-full-mirror-v1",
  commanderspellbookExactDeckDetectorV1Dir: "commanderspellbook-exact-deck-detector-v1",
  historicalCommanderMetaNullAuditV1Dir: "historical-commander-meta-null-audit-v1",
  spellbookWinArchitectureSpaceV1Dir: "spellbook-win-architecture-space-v1",
  spellbookHistoricalOutcomeAssociationV1Dir: "spellbook-historical-outcome-association-v1",
  historicalPodContextGeometryV1Dir: "historical-pod-context-geometry-v1",
  intrinsicDeckOptimizationGeometryV1Dir: "intrinsic-deck-optimization-geometry-v1",
  intrinsicStrengthAblationV1Dir: "intrinsic-strength-ablation-v1",
  commanderOptimizationScoreV1Dir: "commander-optimization-score-v1",
  topdeckFullHistoricalCoverageAuditV1Dir: "topdeck-full-historical-coverage-audit-v1",
  commanderOptimizationScoreV2Dir: "commander-optimization-score-v2",
} as const;

export function mechanicalSpacePath(...parts: string[]): string {
  return resolve(MECHANICAL_SPACE_DIR, ...parts);
}
