/**
 * P0 — explicit disposition for all 36 zero-variance IPV2 axes.
 * v2.1 prunes unsupported vectors rather than fabricating proxies.
 */
import type { DeadAxisDisposition } from "./types";

export type DeadAxisRecord = {
  key: string;
  zone: "mainboard" | "commandZone";
  family: string;
  vector: string;
  rootCause: string;
  disposition: DeadAxisDisposition;
  repair?: string;
  keepOrPrune: "PRUNE";
};

export const IPV2_DEAD_AXIS_DISPOSITIONS: DeadAxisRecord[] = [
  {
    key: "ipv2_mb_creatures_resilience",
    zone: "mainboard",
    family: "creatures",
    vector: "resilience",
    rootCause: "No defensible indestructible/regeneration/shroud mapping in frozen RC8 layer.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_creatures_resilience",
    zone: "commandZone",
    family: "creatures",
    vector: "resilience",
    rootCause: "Command-zone creature recovery/protection not reliably derivable.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_artifacts_reliance",
    zone: "mainboard",
    family: "artifacts",
    vector: "reliance",
    rootCause: "v2 mapped artifact exposure only; artifact-synergy payoffs not implemented.",
    disposition: "IMPLEMENTATION_GAP",
    repair: "v2.1: oracle patterns for artifact synergy (for each artifact, sacrifice artifact payoff, equip).",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_artifacts_reliance",
    zone: "commandZone",
    family: "artifacts",
    vector: "reliance",
    rootCause: "Same as MB; commander artifact-plan reliance unmapped in v2.",
    disposition: "IMPLEMENTATION_GAP",
    repair: "v2.1: artifact synergy on command-zone cards.",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_artifacts_resilience",
    zone: "mainboard",
    family: "artifacts",
    vector: "resilience",
    rootCause: "No deterministic artifact-recovery resistance taxonomy.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_artifacts_resilience",
    zone: "commandZone",
    family: "artifacts",
    vector: "resilience",
    rootCause: "Same as MB artifacts resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_enchantments_reliance",
    zone: "mainboard",
    family: "enchantments",
    vector: "reliance",
    rootCause: "Enchantment synergy engines not mapped (only type-line exposure).",
    disposition: "IMPLEMENTATION_GAP",
    repair: "Defer to future; v2.1 omits enchantment reliance from retained schema.",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_enchantments_reliance",
    zone: "commandZone",
    family: "enchantments",
    vector: "reliance",
    rootCause: "Same as MB enchantment reliance.",
    disposition: "IMPLEMENTATION_GAP",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_lands_disruption",
    zone: "commandZone",
    family: "lands",
    vector: "disruption",
    rootCause: "Command-zone cards virtually never encode land destruction.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_lands_resilience",
    zone: "mainboard",
    family: "lands",
    vector: "resilience",
    rootCause: "Land recursion/crucible signals not in deterministic registry.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_lands_resilience",
    zone: "commandZone",
    family: "lands",
    vector: "resilience",
    rootCause: "Same as MB lands resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_tokens_exposure",
    zone: "mainboard",
    family: "tokens",
    vector: "exposure",
    rootCause: "Tokens are not deck-list permanents; exposure is undefined at deck composition time.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_tokens_exposure",
    zone: "commandZone",
    family: "tokens",
    vector: "exposure",
    rootCause: "Same structural issue as MB token exposure.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_graveyard_exposure",
    zone: "mainboard",
    family: "graveyard",
    vector: "exposure",
    rootCause: "Graveyard zone contents are game-state, not deck composition.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_graveyard_exposure",
    zone: "commandZone",
    family: "graveyard",
    vector: "exposure",
    rootCause: "Same as MB graveyard exposure.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_library_search_disruption",
    zone: "commandZone",
    family: "library_search",
    vector: "disruption",
    rootCause: "Search denial is a mainboard answer; not command-zone mechanic.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_hand_resources_resilience",
    zone: "mainboard",
    family: "hand_resources",
    vector: "resilience",
    rootCause: "Refuel-after-disruption not deterministically mapped.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_hand_resources_resilience",
    zone: "commandZone",
    family: "hand_resources",
    vector: "resilience",
    rootCause: "Same as MB hand resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_exile_resilience",
    zone: "mainboard",
    family: "exile",
    vector: "resilience",
    rootCause: "Exile recovery (e.g. Yawgmoth's Will) not in registry.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_exile_resilience",
    zone: "commandZone",
    family: "exile",
    vector: "resilience",
    rootCause: "Same as MB exile resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_spells_stack_reliance",
    zone: "mainboard",
    family: "spells_stack",
    vector: "reliance",
    rootCause: "v2 mapped instant/sorcery exposure only; spell-chain engine reliance unmapped.",
    disposition: "IMPLEMENTATION_GAP",
    repair: "v2.1: cast triggers, storm, copy, magecraft, prowess patterns.",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_spells_stack_reliance",
    zone: "commandZone",
    family: "spells_stack",
    vector: "reliance",
    rootCause: "Same as MB spells_stack reliance.",
    disposition: "IMPLEMENTATION_GAP",
    repair: "v2.1: spell-engine patterns on commander.",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_spells_stack_resilience",
    zone: "mainboard",
    family: "spells_stack",
    vector: "resilience",
    rootCause: "Can't be countered/recursion protection not mapped.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_spells_stack_resilience",
    zone: "commandZone",
    family: "spells_stack",
    vector: "resilience",
    rootCause: "Same as MB spells_stack resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_activated_abilities_resilience",
    zone: "mainboard",
    family: "activated_abilities",
    vector: "resilience",
    rootCause: "Activated-ability protection not mapped.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_activated_abilities_resilience",
    zone: "commandZone",
    family: "activated_abilities",
    vector: "resilience",
    rootCause: "Same as MB activated resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_triggered_abilities_disruption",
    zone: "mainboard",
    family: "triggered_abilities",
    vector: "disruption",
    rootCause: "Torpor Orb / Hushbringer-style suppression not in RC8 registry.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_triggered_abilities_disruption",
    zone: "commandZone",
    family: "triggered_abilities",
    vector: "disruption",
    rootCause: "Same as MB triggered disruption.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_mana_acceleration_exposure",
    zone: "mainboard",
    family: "mana_acceleration",
    vector: "exposure",
    rootCause: "Ramp is a plan signal (reliance), not a permanent exposure category.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_mana_acceleration_exposure",
    zone: "commandZone",
    family: "mana_acceleration",
    vector: "exposure",
    rootCause: "Same as MB mana exposure.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_mana_acceleration_disruption",
    zone: "mainboard",
    family: "mana_acceleration",
    vector: "disruption",
    rootCause: "Resource denial (Mana Geyser hate) not deterministically mapped.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_mana_acceleration_disruption",
    zone: "commandZone",
    family: "mana_acceleration",
    vector: "disruption",
    rootCause: "Same as MB mana disruption.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_recursion_disruption",
    zone: "mainboard",
    family: "recursion",
    vector: "disruption",
    rootCause: "Recursion hate is graveyard disruption axis, not separate recursion disruption.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_recursion_disruption",
    zone: "commandZone",
    family: "recursion",
    vector: "disruption",
    rootCause: "Same — folded into graveyard disruption.",
    disposition: "STRUCTURALLY_NOT_APPLICABLE",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_mb_recursion_resilience",
    zone: "mainboard",
    family: "recursion",
    vector: "resilience",
    rootCause: "Recursion resilience overlaps graveyard resilience; not separately mapped.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
  {
    key: "ipv2_cmd_recursion_resilience",
    zone: "commandZone",
    family: "recursion",
    vector: "resilience",
    rootCause: "Same as MB recursion resilience.",
    disposition: "UNSUPPORTED_BY_CURRENT_SEMANTICS",
    keepOrPrune: "PRUNE",
  },
];
