/**
 * Blind archetype-discovery holdout v5 — SEALED unbiased evaluation set.
 * Generated by select-and-seal-blind-v5-holdout.ts — do not hand-edit membership.
 */
import { createHash } from "node:crypto";

export type ArchetypeDiscoveryBlindV5Category =
  | "partner_pair"
  | "commander_with_background"
  | "narrow_single_engine"
  | "multiple_legitimate_plans"
  | "broad_composite"
  | "triggered_engine"
  | "activated_engine"
  | "static_state_engine"
  | "static_restriction"
  | "state_dependency"
  | "resource_scaler"
  | "output_multiplier"
  | "cost_dependency"
  | "activated_cost"
  | "combat"
  | "spells_casting"
  | "protection_engine"
  | "attrition_engine"
  | "resource_conversion"
  | "unusual_zones"
  | "graveyard"
  | "artifacts"
  | "enchantments"
  | "tokens"
  | "counters"
  | "lands"
  | "typal"
  | "type_qualified_engine"
  | "tutor_toolbox"
  | "multi_stage_engine";

export type ArchetypeDiscoveryBlindV5CommandZoneConfiguration =
  | "single_commander"
  | "partner_pair"
  | "commander_with_background";

export type ArchetypeDiscoveryBlindV5Case = {
  id: string;
  category: ArchetypeDiscoveryBlindV5Category;
  commandZoneConfiguration: ArchetypeDiscoveryBlindV5CommandZoneConfiguration;
  commanders: string[];
  bracket: 1 | 2 | 3 | 4 | 5;
  notes?: string;
};

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V5: ArchetypeDiscoveryBlindV5Case[] = [
  { id: "blindv5-01-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Leonardo, the Balance", "Reyhan, Last of the Abzan"], bracket: 3 },
  { id: "blindv5-02-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Gorm the Great", "Virtus the Veiled"], bracket: 3 },
  { id: "blindv5-03-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Halana, Kessig Ranger", "Dargo, the Shipwrecker"], bracket: 3 },
  { id: "blindv5-04-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Tana, the Bloodsower", "Radiant, Serra Archangel"], bracket: 3 },
  { id: "blindv5-05-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Krav, the Unredeemed", "Regna, the Redeemer"], bracket: 3 },
  { id: "blindv5-06-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Esior, Wardwing Familiar", "Numa, Joraga Chieftain"], bracket: 3 },
  { id: "blindv5-07-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Cecily, Haunted Mage", "Wernog, Rider's Chaplain"], bracket: 3 },
  { id: "blindv5-08-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Timin, Youthful Geist", "Rhoda, Geist Avenger"], bracket: 3 },
  { id: "blindv5-09-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Tevesh Szat, Doom of Fools", "Nadier, Agent of the Duskenel"], bracket: 3 },
  { id: "blindv5-10-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Breeches, Brazen Plunderer", "Alena, Kessig Trapper"], bracket: 3 },
  { id: "blindv5-10-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Halsin, Emerald Archdruid", "Tavern Brawler"], bracket: 3 },
  { id: "blindv5-11-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Erinis, Gloom Stalker", "Clan Crafter"], bracket: 3 },
  { id: "blindv5-12-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Lulu, Loyal Hollyphant", "Cultist of the Absolute"], bracket: 3 },
  { id: "blindv5-13-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Baeloth Barrityl, Entertainer", "Noble Heritage"], bracket: 3 },
  { id: "blindv5-14-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Abdel Adrian, Gorion's Ward", "Scion of Halaster"], bracket: 3 },
  { id: "blindv5-15-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Safana, Calimport Cutthroat", "Hardy Outlander"], bracket: 3 },
  { id: "blindv5-16-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Zellix, Sanity Flayer", "Acolyte of Bahamut"], bracket: 3 },
  { id: "blindv5-17-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Livaan, Cultist of Tiamat", "Master Chef"], bracket: 3 },
  { id: "blindv5-19-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Dionus, Elvish Archdruid"], bracket: 3 },
  { id: "blindv5-20-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Zuko, Avatar Hunter"], bracket: 3 },
  { id: "blindv5-21-multiple-legitimate-plans", category: "multiple_legitimate_plans", commandZoneConfiguration: "single_commander", commanders: ["Miles Morales // Ultimate Spider-Man"], bracket: 3 },
  { id: "blindv5-22-broad-composite", category: "broad_composite", commandZoneConfiguration: "single_commander", commanders: ["Curie, Emergent Intelligence"], bracket: 3 },
  { id: "blindv5-23-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Elsha, Threefold Master"], bracket: 3 },
  { id: "blindv5-24-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Sauron, the Necromancer"], bracket: 3 },
  { id: "blindv5-25-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Daxos the Returned"], bracket: 3 },
  { id: "blindv5-26-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Shaun & Rebecca, Agents"], bracket: 3 },
  { id: "blindv5-27-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Kaysa"], bracket: 3 },
  { id: "blindv5-28-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Kíli the Resourceful"], bracket: 3 },
  { id: "blindv5-29-static-restriction", category: "static_restriction", commandZoneConfiguration: "single_commander", commanders: ["Hua Tuo, Honored Physician"], bracket: 3 },
  { id: "blindv5-30-state-dependency", category: "state_dependency", commandZoneConfiguration: "single_commander", commanders: ["The Tarrasque"], bracket: 3 },
  { id: "blindv5-31-state-dependency", category: "state_dependency", commandZoneConfiguration: "single_commander", commanders: ["Syr Armont, the Redeemer"], bracket: 3 },
  { id: "blindv5-32-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["The Swarmlord"], bracket: 3 },
  { id: "blindv5-33-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["Seshiro the Anointed"], bracket: 3 },
  { id: "blindv5-34-output-multiplier", category: "output_multiplier", commandZoneConfiguration: "single_commander", commanders: ["Aradesh, the Founder"], bracket: 3 },
  { id: "blindv5-35-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["The Sackville-Bagginses"], bracket: 3 },
  { id: "blindv5-36-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["Ragost, Deft Gastronaut"], bracket: 3 },
  { id: "blindv5-37-activated-cost", category: "activated_cost", commandZoneConfiguration: "single_commander", commanders: ["The Destined Black Mage"], bracket: 3 },
  { id: "blindv5-38-combat", category: "combat", commandZoneConfiguration: "single_commander", commanders: ["Krang, Utrom Warlord"], bracket: 3 },
  { id: "blindv5-39-spells-casting", category: "spells_casting", commandZoneConfiguration: "single_commander", commanders: ["Balmor, Battlemage Captain"], bracket: 3 },
  { id: "blindv5-40-protection-engine", category: "protection_engine", commandZoneConfiguration: "single_commander", commanders: ["King T'Challa // Black Panther, Hope Enduring"], bracket: 3 },
  { id: "blindv5-41-attrition-engine", category: "attrition_engine", commandZoneConfiguration: "single_commander", commanders: ["Kroxa, Titan of Death's Hunger"], bracket: 3 },
  { id: "blindv5-42-resource-conversion", category: "resource_conversion", commandZoneConfiguration: "single_commander", commanders: ["Cyclonus, the Saboteur // Cyclonus, Cybertronian Fighter"], bracket: 3 },
  { id: "blindv5-43-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Geist of Saint Traft"], bracket: 3 },
  { id: "blindv5-44-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Chainer, Dementia Master"], bracket: 3 },
  { id: "blindv5-45-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Mishra, Tamer of Mak Fawa"], bracket: 3 },
  { id: "blindv5-46-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Beluna Grandsquall // Seek Thrills"], bracket: 3 },
  { id: "blindv5-47-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["Kain, Traitorous Dragoon"], bracket: 3 },
  { id: "blindv5-48-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["Scientist Supreme of A.I.M."], bracket: 3 },
  { id: "blindv5-49-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Keranos, God of Storms"], bracket: 3 },
  { id: "blindv5-50-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Terra, Magical Adept // Esper Terra"], bracket: 3 },
  { id: "blindv5-51-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["Orvar, the All-Form"], bracket: 3 },
  { id: "blindv5-52-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["Zaxara, the Exemplary"], bracket: 3 },
  { id: "blindv5-53-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Nita, Forum Conciliator"], bracket: 3 },
  { id: "blindv5-54-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Kresh the Bloodbraided"], bracket: 3 },
  { id: "blindv5-55-lands", category: "lands", commandZoneConfiguration: "single_commander", commanders: ["Astrid Peth"], bracket: 3 },
  { id: "blindv5-56-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Ezuri, Claw of Progress"], bracket: 3 },
  { id: "blindv5-57-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Anim Pakal, Thousandth Moon"], bracket: 3 },
  { id: "blindv5-58-type-qualified-engine", category: "type_qualified_engine", commandZoneConfiguration: "single_commander", commanders: ["Qala, Ajani's Pridemate"], bracket: 3 },
  { id: "blindv5-59-tutor-toolbox", category: "tutor_toolbox", commandZoneConfiguration: "single_commander", commanders: ["The Earth King"], bracket: 3 },
  { id: "blindv5-60-multi-stage-engine", category: "multi_stage_engine", commandZoneConfiguration: "single_commander", commanders: ["Neyith of the Dire Hunt"], bracket: 3 },
];

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V5_VERSION = "archetype-discovery-blind-holdout-v5";
export const ARCHETYPE_DISCOVERY_BLIND_V5_STATUS = "SEALED" as const;
export const ARCHETYPE_DISCOVERY_BLIND_V5_SELECTION_SEED = "archetype-discovery-blind-v5-seed-20260812";

export function blindHoldoutV5SetHash(): string {
  return createHash("sha256").update(JSON.stringify(ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V5)).digest("hex");
}

export function blindHoldoutV5CategoryComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V5) {
    out[c.category] = (out[c.category] ?? 0) + 1;
  }
  return out;
}

export function blindHoldoutV5CommandZoneComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V5) {
    out[c.commandZoneConfiguration] = (out[c.commandZoneConfiguration] ?? 0) + 1;
  }
  return out;
}
