/**
 * Blind archetype-discovery holdout v4 — SEALED unbiased evaluation set.
 * Generated by select-and-seal-blind-v4-holdout.ts — do not hand-edit membership.
 */
import { createHash } from "node:crypto";

export type ArchetypeDiscoveryBlindV4Category =
  | "partner_pair"
  | "commander_with_background"
  | "narrow_single_engine"
  | "multiple_legitimate_plans"
  | "broad_composite"
  | "triggered_engine"
  | "activated_engine"
  | "static_state_engine"
  | "static_restriction"
  | "state_dependency"
  | "resource_scaler"
  | "output_multiplier"
  | "cost_dependency"
  | "activated_cost"
  | "combat"
  | "spells_casting"
  | "protection_engine"
  | "attrition_engine"
  | "resource_conversion"
  | "unusual_zones"
  | "graveyard"
  | "artifacts"
  | "enchantments"
  | "tokens"
  | "counters"
  | "lands"
  | "typal"
  | "type_qualified_engine"
  | "tutor_toolbox"
  | "multi_stage_engine"
  | "unusual_mechanical";

export type ArchetypeDiscoveryBlindV4CommandZoneConfiguration =
  | "single_commander"
  | "partner_pair"
  | "commander_with_background";

export type ArchetypeDiscoveryBlindV4Case = {
  id: string;
  category: ArchetypeDiscoveryBlindV4Category;
  commandZoneConfiguration: ArchetypeDiscoveryBlindV4CommandZoneConfiguration;
  commanders: string[];
  bracket: 1 | 2 | 3 | 4 | 5;
  notes?: string;
};

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V4: ArchetypeDiscoveryBlindV4Case[] = [
  { id: "blindv4-01-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Vial Smasher the Fierce", "Akroma, Vision of Ixidor"], bracket: 3 },
  { id: "blindv4-02-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Madame Vastra", "Jenny Flint"], bracket: 3 },
  { id: "blindv4-03-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Mr. Wiggles, Helpful Butterfly", "Ignacio of Myra's Marvels"], bracket: 3 },
  { id: "blindv4-04-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Amy Pond", "Rory Williams"], bracket: 3 },
  { id: "blindv4-05-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Pir, Imaginative Rascal", "Toothy, Imaginary Friend"], bracket: 3 },
  { id: "blindv4-06-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Miara, Thorn of the Glade", "Francisco, Fowl Marauder"], bracket: 3 },
  { id: "blindv4-06-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Karlach, Fury of Avernus", "Flaming Fist"], bracket: 3 },
  { id: "blindv4-07-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Jaheira, Friend of the Forest", "Far Traveler"], bracket: 3 },
  { id: "blindv4-08-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Durnan of the Yawning Portal", "Dragon Cultist"], bracket: 3 },
  { id: "blindv4-09-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Skanos Dragonheart", "Faceless One"], bracket: 3 },
  { id: "blindv4-10-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Burakos, Party Leader", "Feywild Visitor"], bracket: 3 },
  { id: "blindv4-11-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Vhal, Candlekeep Researcher", "Inspiring Leader"], bracket: 3 },
  { id: "blindv4-13-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Monk Gyatso"], bracket: 3 },
  { id: "blindv4-14-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Vraska, the Silencer"], bracket: 3 },
  { id: "blindv4-15-multiple-legitimate-plans", category: "multiple_legitimate_plans", commandZoneConfiguration: "single_commander", commanders: ["Aphelia, Viper Whisperer"], bracket: 3 },
  { id: "blindv4-16-broad-composite", category: "broad_composite", commandZoneConfiguration: "single_commander", commanders: ["Kate Stewart"], bracket: 3 },
  { id: "blindv4-17-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Elrond of the White Council"], bracket: 3 },
  { id: "blindv4-18-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Dong Zhou, the Tyrant"], bracket: 3 },
  { id: "blindv4-19-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Grand Marshal Macie"], bracket: 3 },
  { id: "blindv4-20-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Mannichi, the Fevered Dream"], bracket: 3 },
  { id: "blindv4-21-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Arcades Sabboth"], bracket: 3 },
  { id: "blindv4-22-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Fíli the Pathfinder"], bracket: 3 },
  { id: "blindv4-23-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Queen Allenal of Ruadach"], bracket: 3 },
  { id: "blindv4-24-static-restriction", category: "static_restriction", commandZoneConfiguration: "single_commander", commanders: ["Hallar, the Firefletcher"], bracket: 3 },
  { id: "blindv4-25-state-dependency", category: "state_dependency", commandZoneConfiguration: "single_commander", commanders: ["Narci, Fable Singer"], bracket: 3 },
  { id: "blindv4-26-state-dependency", category: "state_dependency", commandZoneConfiguration: "single_commander", commanders: ["Commander Liara Portyr"], bracket: 3 },
  { id: "blindv4-27-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["Giada, Font of Hope"], bracket: 3 },
  { id: "blindv4-28-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["Vaan, Street Thief"], bracket: 3 },
  { id: "blindv4-29-output-multiplier", category: "output_multiplier", commandZoneConfiguration: "single_commander", commanders: ["Huatli, Poet of Unity // Roar of the Fifth People"], bracket: 3 },
  { id: "blindv4-30-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["Ronin, Shadow Stalker"], bracket: 3 },
  { id: "blindv4-31-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["Vona, Butcher of Magan"], bracket: 3 },
  { id: "blindv4-32-activated-cost", category: "activated_cost", commandZoneConfiguration: "single_commander", commanders: ["Svella, Ice Shaper"], bracket: 3 },
  { id: "blindv4-33-combat", category: "combat", commandZoneConfiguration: "single_commander", commanders: ["Chiss-Goria, Forge Tyrant"], bracket: 3 },
  { id: "blindv4-34-combat", category: "combat", commandZoneConfiguration: "single_commander", commanders: ["Kazuul, Tyrant of the Cliffs"], bracket: 3 },
  { id: "blindv4-35-spells-casting", category: "spells_casting", commandZoneConfiguration: "single_commander", commanders: ["Y'shtola, Night's Blessed"], bracket: 3 },
  { id: "blindv4-36-spells-casting", category: "spells_casting", commandZoneConfiguration: "single_commander", commanders: ["Wiccan, Rising Magician"], bracket: 3 },
  { id: "blindv4-37-protection-engine", category: "protection_engine", commandZoneConfiguration: "single_commander", commanders: ["Tresserhorn's Lord, Returned"], bracket: 3 },
  { id: "blindv4-38-attrition-engine", category: "attrition_engine", commandZoneConfiguration: "single_commander", commanders: ["Xavier Sal, Infested Captain"], bracket: 3 },
  { id: "blindv4-39-resource-conversion", category: "resource_conversion", commandZoneConfiguration: "single_commander", commanders: ["Saheeli, the Gifted"], bracket: 3 },
  { id: "blindv4-40-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Gideon, Champion of Justice"], bracket: 3 },
  { id: "blindv4-41-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Gisa, Glorious Resurrector"], bracket: 3 },
  { id: "blindv4-42-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Tymaret, Chosen from Death"], bracket: 3 },
  { id: "blindv4-43-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Bilbo, Thief in the Night"], bracket: 3 },
  { id: "blindv4-44-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["Jorn, God of Winter // Kaldring, the Rimestaff"], bracket: 3 },
  { id: "blindv4-45-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["Pia Nalaar, Consul of Revival"], bracket: 3 },
  { id: "blindv4-46-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Chishiro, the Shattered Blade"], bracket: 3 },
  { id: "blindv4-47-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Nevinyrral, Urborg Tyrant"], bracket: 3 },
  { id: "blindv4-48-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["Sidisi, Brood Tyrant"], bracket: 3 },
  { id: "blindv4-49-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["Arnim Zola, Bio-Fanatic"], bracket: 3 },
  { id: "blindv4-50-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Dr. Beverly Crusher"], bracket: 3 },
  { id: "blindv4-51-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Venat, Heart of Hydaelyn // Hydaelyn, the Mothercrystal"], bracket: 3 },
  { id: "blindv4-52-lands", category: "lands", commandZoneConfiguration: "single_commander", commanders: ["Tatyova, Benthic Druid"], bracket: 3 },
  { id: "blindv4-53-lands", category: "lands", commandZoneConfiguration: "single_commander", commanders: ["Zar Ojanen, Scion of Efrava"], bracket: 3 },
  { id: "blindv4-54-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Shiko and Narset, Unified"], bracket: 3 },
  { id: "blindv4-55-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Massimo, the Magician"], bracket: 3 },
  { id: "blindv4-56-type-qualified-engine", category: "type_qualified_engine", commandZoneConfiguration: "single_commander", commanders: ["Captain America, Steve Rogers"], bracket: 3 },
  { id: "blindv4-57-tutor-toolbox", category: "tutor_toolbox", commandZoneConfiguration: "single_commander", commanders: ["Nahiri, the Harbinger"], bracket: 3 },
  { id: "blindv4-58-tutor-toolbox", category: "tutor_toolbox", commandZoneConfiguration: "single_commander", commanders: ["Kaho, Minamo Historian"], bracket: 3 },
  { id: "blindv4-59-multi-stage-engine", category: "multi_stage_engine", commandZoneConfiguration: "single_commander", commanders: ["Ink-Eyes, Servant of Oni"], bracket: 3 },
  { id: "blindv4-60-unusual-mechanical", category: "unusual_mechanical", commandZoneConfiguration: "single_commander", commanders: ["Nick Fury, Agent of S.H.I.E.L.D."], bracket: 3 },
];

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V4_VERSION = "archetype-discovery-blind-holdout-v4";
export const ARCHETYPE_DISCOVERY_BLIND_V4_STATUS = "SEALED" as const;
export const ARCHETYPE_DISCOVERY_BLIND_V4_SELECTION_SEED = "archetype-discovery-blind-v4-seed-20260812";

export function blindHoldoutV4SetHash(): string {
  return createHash("sha256").update(JSON.stringify(ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V4)).digest("hex");
}

export function blindHoldoutV4CategoryComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V4) {
    out[c.category] = (out[c.category] ?? 0) + 1;
  }
  return out;
}

export function blindHoldoutV4CommandZoneComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V4) {
    out[c.commandZoneConfiguration] = (out[c.commandZoneConfiguration] ?? 0) + 1;
  }
  return out;
}
