/**
 * Blind archetype-discovery holdout v3 — SEALED unbiased evaluation set.
 * Generated by select-and-seal-blind-v3-holdout.ts — do not hand-edit membership.
 */
import { createHash } from "node:crypto";

export type ArchetypeDiscoveryBlindV3Category =
  | "partner_pair"
  | "commander_with_background"
  | "narrow_single_engine"
  | "multiple_legitimate_plans"
  | "broad_composite"
  | "triggered_engine"
  | "activated_engine"
  | "static_state_engine"
  | "resource_scaler"
  | "cost_dependency"
  | "combat"
  | "spells_casting"
  | "unusual_zones"
  | "graveyard"
  | "artifacts"
  | "enchantments"
  | "tokens"
  | "counters"
  | "lands"
  | "typal"
  | "tutor_toolbox"
  | "multi_stage_engine"
  | "unusual_mechanical";

export type ArchetypeDiscoveryBlindV3CommandZoneConfiguration =
  | "single_commander"
  | "partner_pair"
  | "commander_with_background";

export type ArchetypeDiscoveryBlindV3Case = {
  id: string;
  category: ArchetypeDiscoveryBlindV3Category;
  commandZoneConfiguration: ArchetypeDiscoveryBlindV3CommandZoneConfiguration;
  commanders: string[];
  bracket: 1 | 2 | 3 | 4 | 5;
  notes?: string;
};

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V3: ArchetypeDiscoveryBlindV3Case[] = [
  { id: "blindv3-01-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Silvar, Devourer of the Free", "Trynn, Champion of Freedom"], bracket: 3 },
  { id: "blindv3-02-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Auntie Flint", "Anara, Wolvid Familiar"], bracket: 3 },
  { id: "blindv3-03-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Khorvath Brightflame", "Sylvia Brightspear"], bracket: 3 },
  { id: "blindv3-04-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Alphinaud Leveilleur", "Alisaie Leveilleur"], bracket: 3 },
  { id: "blindv3-05-partner-pair", category: "partner_pair", commandZoneConfiguration: "partner_pair", commanders: ["Raphael, the Muscle", "Jeska, Thrice Reborn"], bracket: 3 },
  { id: "blindv3-05-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Sarevok, Deathbringer", "Folk Hero"], bracket: 3 },
  { id: "blindv3-06-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Sivriss, Nightmare Speaker", "Sword Coast Sailor"], bracket: 3 },
  { id: "blindv3-07-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Ellyn Harbreeze, Busybody", "Candlekeep Sage"], bracket: 3 },
  { id: "blindv3-08-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Imoen, Mystic Trickster", "Guild Artisan"], bracket: 3 },
  { id: "blindv3-09-commander-background", category: "commander_with_background", commandZoneConfiguration: "commander_with_background", commanders: ["Gale, Waterdeep Prodigy", "Wizard from Beyond"], bracket: 3 },
  { id: "blindv3-11-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Gerrard Capashen"], bracket: 3 },
  { id: "blindv3-12-narrow-single-engine", category: "narrow_single_engine", commandZoneConfiguration: "single_commander", commanders: ["Stonebrow, Krosan Hero"], bracket: 3 },
  { id: "blindv3-13-multiple-legitimate-plans", category: "multiple_legitimate_plans", commandZoneConfiguration: "single_commander", commanders: ["Zacama, Primal Calamity"], bracket: 3 },
  { id: "blindv3-14-multiple-legitimate-plans", category: "multiple_legitimate_plans", commandZoneConfiguration: "single_commander", commanders: ["Kellan, Planar Trailblazer"], bracket: 3 },
  { id: "blindv3-15-broad-composite", category: "broad_composite", commandZoneConfiguration: "single_commander", commanders: ["MacCready, Lamplight Mayor"], bracket: 3 },
  { id: "blindv3-16-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Kestia, the Cultivator"], bracket: 3 },
  { id: "blindv3-17-triggered-engine", category: "triggered_engine", commandZoneConfiguration: "single_commander", commanders: ["Zhang He, Wei General"], bracket: 3 },
  { id: "blindv3-18-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Zedruu the Greathearted"], bracket: 3 },
  { id: "blindv3-19-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Magus Lucea Kane"], bracket: 3 },
  { id: "blindv3-20-activated-engine", category: "activated_engine", commandZoneConfiguration: "single_commander", commanders: ["Experiment Kraj"], bracket: 3 },
  { id: "blindv3-21-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Marrow-Gnawer"], bracket: 3 },
  { id: "blindv3-22-static-state-engine", category: "static_state_engine", commandZoneConfiguration: "single_commander", commanders: ["Plargg, Dean of Chaos // Augusta, Dean of Order"], bracket: 3 },
  { id: "blindv3-23-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["Rashmi and Ragavan"], bracket: 3 },
  { id: "blindv3-24-resource-scaler", category: "resource_scaler", commandZoneConfiguration: "single_commander", commanders: ["Valeria Richards, Precocious"], bracket: 3 },
  { id: "blindv3-25-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["Glóin, Dwarf Emissary"], bracket: 3 },
  { id: "blindv3-26-cost-dependency", category: "cost_dependency", commandZoneConfiguration: "single_commander", commanders: ["The Master of Cuisine"], bracket: 3 },
  { id: "blindv3-27-combat", category: "combat", commandZoneConfiguration: "single_commander", commanders: ["Emrakul and Chatterfang"], bracket: 3 },
  { id: "blindv3-28-combat", category: "combat", commandZoneConfiguration: "single_commander", commanders: ["Sarkhan the Masterless"], bracket: 3 },
  { id: "blindv3-29-spells-casting", category: "spells_casting", commandZoneConfiguration: "single_commander", commanders: ["Birgi, God of Storytelling // Harnfel, Horn of Bounty"], bracket: 3 },
  { id: "blindv3-30-spells-casting", category: "spells_casting", commandZoneConfiguration: "single_commander", commanders: ["Teferi, Time Raveler"], bracket: 3 },
  { id: "blindv3-31-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Kari Zev, Skyship Raider"], bracket: 3 },
  { id: "blindv3-32-unusual-zones", category: "unusual_zones", commandZoneConfiguration: "single_commander", commanders: ["Rayami, First of the Fallen"], bracket: 3 },
  { id: "blindv3-33-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Bumi, King of Three Trials"], bracket: 3 },
  { id: "blindv3-34-graveyard", category: "graveyard", commandZoneConfiguration: "single_commander", commanders: ["Moseo, Vein's New Dean"], bracket: 3 },
  { id: "blindv3-35-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["Bofur, Reliable Guardian // Concerted Care"], bracket: 3 },
  { id: "blindv3-36-artifacts", category: "artifacts", commandZoneConfiguration: "single_commander", commanders: ["June, Bounty Hunter"], bracket: 3 },
  { id: "blindv3-37-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Go-Shintai of Ancient Wars"], bracket: 3 },
  { id: "blindv3-38-enchantments", category: "enchantments", commandZoneConfiguration: "single_commander", commanders: ["Eriette of the Charmed Apple"], bracket: 3 },
  { id: "blindv3-39-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["The Caffeinated Runner"], bracket: 3 },
  { id: "blindv3-40-tokens", category: "tokens", commandZoneConfiguration: "single_commander", commanders: ["Urza, Planeswalker"], bracket: 3 },
  { id: "blindv3-41-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Vincent, Vengeful Atoner"], bracket: 3 },
  { id: "blindv3-42-counters", category: "counters", commandZoneConfiguration: "single_commander", commanders: ["Hapatra, Vizier of Poisons"], bracket: 3 },
  { id: "blindv3-43-lands", category: "lands", commandZoneConfiguration: "single_commander", commanders: ["Toph, Hardheaded Teacher"], bracket: 3 },
  { id: "blindv3-44-lands", category: "lands", commandZoneConfiguration: "single_commander", commanders: ["Black Panther, Wakandan King"], bracket: 3 },
  { id: "blindv3-45-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Kwain, Itinerant Meddler"], bracket: 3 },
  { id: "blindv3-46-typal", category: "typal", commandZoneConfiguration: "single_commander", commanders: ["Zack Fair"], bracket: 3 },
  { id: "blindv3-47-tutor-toolbox", category: "tutor_toolbox", commandZoneConfiguration: "single_commander", commanders: ["Karametra, God of Harvests"], bracket: 3 },
  { id: "blindv3-48-tutor-toolbox", category: "tutor_toolbox", commandZoneConfiguration: "single_commander", commanders: ["Sivitri, Dragon Master"], bracket: 3 },
  { id: "blindv3-49-multi-stage-engine", category: "multi_stage_engine", commandZoneConfiguration: "single_commander", commanders: ["The Great Juggernaut"], bracket: 3 },
  { id: "blindv3-50-unusual-mechanical", category: "unusual_mechanical", commandZoneConfiguration: "single_commander", commanders: ["Nethroi, Apex of Death"], bracket: 3 },
];

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V3_VERSION = "archetype-discovery-blind-holdout-v3";
export const ARCHETYPE_DISCOVERY_BLIND_V3_STATUS = "SPENT" as const;
export const ARCHETYPE_DISCOVERY_BLIND_V3_SELECTION_SEED = "archetype-discovery-blind-v3-seed-20260812";

export function blindHoldoutV3SetHash(): string {
  return createHash("sha256").update(JSON.stringify(ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V3)).digest("hex");
}

export function blindHoldoutV3CategoryComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V3) {
    out[c.category] = (out[c.category] ?? 0) + 1;
  }
  return out;
}

export function blindHoldoutV3CommandZoneComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V3) {
    out[c.commandZoneConfiguration] = (out[c.commandZoneConfiguration] ?? 0) + 1;
  }
  return out;
}
