/**
 * Blind archetype-discovery holdout v2 — SEALED unbiased evaluation set.
 * Generated by select-and-seal-blind-v2-holdout.ts — do not hand-edit membership.
 */
import { createHash } from "node:crypto";

export type ArchetypeDiscoveryBlindV2Category =
  | "narrow_single_engine"
  | "multiple_legitimate_plans"
  | "broad_open_ended"
  | "combat_attack"
  | "damage_life"
  | "spells_casting"
  | "exile_unusual_zones"
  | "graveyard"
  | "artifacts"
  | "enchantments"
  | "counters"
  | "tokens"
  | "lands"
  | "typal"
  | "activated_engine"
  | "triggered_engine"
  | "cost_driven_engine"
  | "resource_conversion"
  | "partner_background"
  | "unusual_mechanical";

export type ArchetypeDiscoveryBlindV2Case = {
  id: string;
  category: ArchetypeDiscoveryBlindV2Category;
  commanders: string[];
  bracket: 1 | 2 | 3 | 4 | 5;
  notes?: string;
};

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V2: ArchetypeDiscoveryBlindV2Case[] = [
  { id: "blindv2-01-narrow-single-engine", category: "narrow_single_engine", commanders: ["Ruxa, Patient Professor"], bracket: 3 },
  { id: "blindv2-02-narrow-single-engine", category: "narrow_single_engine", commanders: ["Martha Jones"], bracket: 3 },
  { id: "blindv2-03-narrow-single-engine", category: "narrow_single_engine", commanders: ["Haunted One"], bracket: 3 },
  { id: "blindv2-04-multiple-legitimate-plans", category: "multiple_legitimate_plans", commanders: ["Etrata, Deadly Fugitive"], bracket: 3 },
  { id: "blindv2-05-multiple-legitimate-plans", category: "multiple_legitimate_plans", commanders: ["Lulu, Stern Guardian"], bracket: 3 },
  { id: "blindv2-06-multiple-legitimate-plans", category: "multiple_legitimate_plans", commanders: ["Arwen Undómiel"], bracket: 3 },
  { id: "blindv2-07-broad-open-ended", category: "broad_open_ended", commanders: ["The Rise of Sozin // Fire Lord Sozin"], bracket: 3 },
  { id: "blindv2-08-broad-open-ended", category: "broad_open_ended", commanders: ["Human Torch"], bracket: 3 },
  { id: "blindv2-09-combat-attack", category: "combat_attack", commanders: ["The Wise Mothman"], bracket: 3 },
  { id: "blindv2-10-combat-attack", category: "combat_attack", commanders: ["Ruric Thar, the Unbowed"], bracket: 3 },
  { id: "blindv2-11-combat-attack", category: "combat_attack", commanders: ["Zareth San, the Trickster"], bracket: 3 },
  { id: "blindv2-12-damage-life", category: "damage_life", commanders: ["Glissa Sunslayer"], bracket: 3 },
  { id: "blindv2-13-damage-life", category: "damage_life", commanders: ["Legolas Greenleaf"], bracket: 3 },
  { id: "blindv2-14-spells-casting", category: "spells_casting", commanders: ["Narset Transcendent"], bracket: 3 },
  { id: "blindv2-15-spells-casting", category: "spells_casting", commanders: ["Nicol Bolas, the Ravager // Nicol Bolas, the Arisen"], bracket: 3 },
  { id: "blindv2-16-spells-casting", category: "spells_casting", commanders: ["Extus, Oriq Overlord // Awaken the Blood Avatar"], bracket: 3 },
  { id: "blindv2-17-exile-unusual-zones", category: "exile_unusual_zones", commanders: ["Oona, Queen of the Fae"], bracket: 3 },
  { id: "blindv2-18-exile-unusual-zones", category: "exile_unusual_zones", commanders: ["Ian Malcolm, Chaotician"], bracket: 3 },
  { id: "blindv2-19-graveyard", category: "graveyard", commanders: ["Spider-Man, To the Rescue"], bracket: 3 },
  { id: "blindv2-20-graveyard", category: "graveyard", commanders: ["Jacob Frye"], bracket: 3 },
  { id: "blindv2-21-graveyard", category: "graveyard", commanders: ["Amzu, Swarm's Hunger"], bracket: 3 },
  { id: "blindv2-22-artifacts", category: "artifacts", commanders: ["Jetfire, Ingenious Scientist // Jetfire, Air Guardian"], bracket: 3 },
  { id: "blindv2-23-artifacts", category: "artifacts", commanders: ["Rendmaw, Creaking Nest"], bracket: 3 },
  { id: "blindv2-24-artifacts", category: "artifacts", commanders: ["Lazav, Wearer of Faces"], bracket: 3 },
  { id: "blindv2-25-enchantments", category: "enchantments", commanders: ["Bruna, Light of Alabaster"], bracket: 3 },
  { id: "blindv2-26-enchantments", category: "enchantments", commanders: ["Erayo, Soratami Ascendant // Erayo's Essence"], bracket: 3 },
  { id: "blindv2-27-counters", category: "counters", commanders: ["Cult of Skaro"], bracket: 3 },
  { id: "blindv2-28-counters", category: "counters", commanders: ["Wyll, Blade of Frontiers"], bracket: 3 },
  { id: "blindv2-29-tokens", category: "tokens", commanders: ["The Waffle Restaurant"], bracket: 3 },
  { id: "blindv2-30-tokens", category: "tokens", commanders: ["Mzed, Mercenary Leader"], bracket: 3 },
  { id: "blindv2-31-tokens", category: "tokens", commanders: ["Tetzin, Gnome Champion // The Golden-Gear Colossus"], bracket: 3 },
  { id: "blindv2-32-lands", category: "lands", commanders: ["Rulik Mons, Warren Chief"], bracket: 3 },
  { id: "blindv2-33-lands", category: "lands", commanders: ["Maraxus of Keld"], bracket: 3 },
  { id: "blindv2-34-typal", category: "typal", commanders: ["Johann, Apprentice Sorcerer"], bracket: 3 },
  { id: "blindv2-35-typal", category: "typal", commanders: ["Mirri the Cursed"], bracket: 3 },
  { id: "blindv2-36-activated-engine", category: "activated_engine", commanders: ["Urianger Augurelt"], bracket: 3 },
  { id: "blindv2-37-activated-engine", category: "activated_engine", commanders: ["Kazarov, Sengir Pureblood"], bracket: 3 },
  { id: "blindv2-38-activated-engine", category: "activated_engine", commanders: ["Lady Caleria"], bracket: 3 },
  { id: "blindv2-39-triggered-engine", category: "triggered_engine", commanders: ["Captain James T. Kirk"], bracket: 3 },
  { id: "blindv2-40-triggered-engine", category: "triggered_engine", commanders: ["Kellan, the Kid"], bracket: 3 },
  { id: "blindv2-41-triggered-engine", category: "triggered_engine", commanders: ["Go-Shintai of Lost Wisdom"], bracket: 3 },
  { id: "blindv2-42-cost-driven-engine", category: "cost_driven_engine", commanders: ["The Wandering Rescuer"], bracket: 3 },
  { id: "blindv2-43-cost-driven-engine", category: "cost_driven_engine", commanders: ["Griselbrand"], bracket: 3 },
  { id: "blindv2-44-resource-conversion", category: "resource_conversion", commanders: ["The Good Time Sleuth"], bracket: 3 },
  { id: "blindv2-45-resource-conversion", category: "resource_conversion", commanders: ["Elminster"], bracket: 3 },
  { id: "blindv2-46-partner-background", category: "partner_background", commanders: ["Bruse Tarl, Boorish Herder"], bracket: 3 },
  { id: "blindv2-47-partner-background", category: "partner_background", commanders: ["Enolc, Perfect Clone"], bracket: 3 },
  { id: "blindv2-48-partner-background", category: "partner_background", commanders: ["Ganax, Astral Hunter"], bracket: 3 },
  { id: "blindv2-49-unusual-mechanical", category: "unusual_mechanical", commanders: ["Adric, Mathematical Genius"], bracket: 3 },
  { id: "blindv2-50-unusual-mechanical", category: "unusual_mechanical", commanders: ["The Legend of Yangchen // Avatar Yangchen"], bracket: 3 },
];

export const ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V2_VERSION = "archetype-discovery-blind-holdout-v2";
export const ARCHETYPE_DISCOVERY_BLIND_V2_STATUS = "DEVELOPMENT_DIAGNOSTIC_SPENT" as const;

export function blindHoldoutV2SetHash(): string {
  return createHash("sha256").update(JSON.stringify(ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V2)).digest("hex");
}

export function blindHoldoutV2CategoryComposition(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of ARCHETYPE_DISCOVERY_BLIND_HOLDOUT_V2) {
    out[c.category] = (out[c.category] ?? 0) + 1;
  }
  return out;
}
