/**
 * Mechanical engine patterns — label-independent discovery templates.
 * Human labels are mapped post-hoc; patterns drive classification.
 */
import type { ArchetypeKind, EnginePatternDef } from "./archetype-discovery-types-v1";

const RAW_MECHANICAL_ENGINE_PATTERNS_V1: Omit<EnginePatternDef, "archetypeKind">[] = [
  {
    patternId: "graveyard_recursion_engine",
    mechanicalName: "Graveyard Recursion Engine",
    primaryAxes: ["graveyard", "recursion"],
    secondaryAxes: ["creatures", "hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "cards_to_graveyard" },
      { stage: "ENABLER", mechanic: "graveyard_setup" },
      { stage: "ENGINE", mechanic: "recursion_reanimation" },
      { stage: "PAYOFF", mechanic: "repeated_etb_death_value" },
      { stage: "WIN", mechanic: "engine_advantage_or_combat" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "cards_to_graveyard", targetMechanic: "graveyard_setup", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "graveyard_setup", targetMechanic: "recursion_reanimation", relationship: "enables" },
      { sourceStage: "ENGINE", targetStage: "PAYOFF", sourceMechanic: "recursion_reanimation", targetMechanic: "repeated_etb_death_value", relationship: "converts" },
      { sourceStage: "PAYOFF", targetStage: "WIN", sourceMechanic: "repeated_etb_death_value", targetMechanic: "engine_advantage_or_combat", relationship: "feeds" },
    ],
    commanderRoleWeights: { graveyard_setup: 0.9, reanimation: 1, recursion: 0.8 },
    commanderAxisKeys: ["ipv2_1_cmd_graveyard_reliance", "ipv2_1_cmd_recursion_reliance"],
    commanderAxisWeights: [1, 0.8],
    requiredFunctions: ["graveyard_setup", "recursion", "payoff_conversion"],
    supportingFunctions: ["protection", "card_advantage", "mana"],
    catalogRoleBuckets: {
      enablers: ["graveyard_setup", "mill"],
      enginePieces: ["recursion", "reanimation"],
      payoffs: ["combat_payoff", "card_advantage", "sacrifice_payoff"],
      redundancy: ["recursion", "reanimation", "graveyard_setup"],
      resourceSupport: ["ramp", "card_draw", "mana_generation"],
      interactionProtection: ["removal", "protection", "board_wipe"],
      finishers: ["combat_payoff", "reanimation"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 12, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["graveyard_value", "recursion_loop", "reanimation_threats"],
    structuralDemands: ["graveyard_enablers", "recursion_redundancy", "interaction"],
    incidentalRoles: ["graveyard_setup"],
    incidentalMaxScore: 0.22,
    bracketIntentSignals: { comboDensity: 0.3, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "sacrifice_death_trigger_engine",
    mechanicalName: "Sacrifice / Death Trigger Engine",
    primaryAxes: ["creatures", "tokens"],
    secondaryAxes: ["graveyard", "hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "creatures_or_tokens" },
      { stage: "ENABLER", mechanic: "sacrifice_outlet" },
      { stage: "ENGINE", mechanic: "death_triggers" },
      { stage: "PAYOFF", mechanic: "drain_or_card_advantage" },
      { stage: "WIN", mechanic: "incremental_or_combo" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "creatures_or_tokens", targetMechanic: "sacrifice_outlet", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "sacrifice_outlet", targetMechanic: "death_triggers", relationship: "enables" },
      { sourceStage: "ENGINE", targetStage: "PAYOFF", sourceMechanic: "death_triggers", targetMechanic: "drain_or_card_advantage", relationship: "converts" },
    ],
    commanderRoleWeights: { sacrifice_outlet: 0.9, sacrifice_payoff: 1, token_generation: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance", "ipv2_1_cmd_tokens_reliance"],
    commanderAxisWeights: [0.8, 0.5],
    requiredFunctions: ["sacrifice_outlet", "death_payoff", "token_or_creature_supply"],
    supportingFunctions: ["recursion", "protection"],
    catalogRoleBuckets: {
      enablers: ["sacrifice_outlet", "token_generation"],
      enginePieces: ["sacrifice_payoff", "sacrifice_outlet"],
      payoffs: ["sacrifice_payoff", "life_loss", "card_draw"],
      redundancy: ["sacrifice_outlet", "sacrifice_payoff", "token_generation"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["life_loss", "combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 12, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["aristocrats", "death_triggers", "drain"],
    structuralDemands: ["outlets", "payoffs", "creatures_or_tokens"],
    incidentalRoles: ["token_generation", "sacrifice_outlet"],
    incidentalMaxScore: 0.25,
    bracketIntentSignals: { comboDensity: 0.35, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "token_swarm_engine",
    mechanicalName: "Token Production Engine",
    primaryAxes: ["tokens", "creatures"],
    secondaryAxes: ["combat_payoff"],
    chain: [
      { stage: "INPUT", mechanic: "mana_and_board" },
      { stage: "ENABLER", mechanic: "token_production" },
      { stage: "ENGINE", mechanic: "token_multipliers" },
      { stage: "PAYOFF", mechanic: "anthems_or_sacrifice" },
      { stage: "WIN", mechanic: "combat_overrun" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "mana_and_board", targetMechanic: "token_production", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "token_production", targetMechanic: "token_multipliers", relationship: "feeds" },
      { sourceStage: "ENGINE", targetStage: "PAYOFF", sourceMechanic: "token_multipliers", targetMechanic: "anthems_or_sacrifice", relationship: "converts" },
    ],
    commanderRoleWeights: { token_generation: 1, combat_payoff: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_tokens_reliance", "ipv2_1_cmd_creatures_reliance"],
    commanderAxisWeights: [1, 0.6],
    requiredFunctions: ["token_production", "payoff_conversion"],
    supportingFunctions: ["ramp", "protection"],
    catalogRoleBuckets: {
      enablers: ["token_generation", "ramp"],
      enginePieces: ["token_generation", "combat_manipulation"],
      payoffs: ["combat_payoff", "sacrifice_payoff"],
      redundancy: ["token_generation"],
      resourceSupport: ["ramp", "mana_generation"],
      interactionProtection: ["removal", "board_wipe", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.42,
    minCatalogCounts: { enablers: 10, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 12, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["go_wide", "token_combat"],
    structuralDemands: ["token_producers", "payoffs", "ramp"],
    incidentalRoles: ["token_generation"],
    incidentalMaxScore: 0.28,
    bracketIntentSignals: { comboDensity: 0.1, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "spellslinger_chain_engine",
    mechanicalName: "Instant/Sorcery Chain Engine",
    primaryAxes: ["spells_stack", "hand_resources"],
    secondaryAxes: ["recursion"],
    chain: [
      { stage: "INPUT", mechanic: "cheap_spells" },
      { stage: "ENABLER", mechanic: "spell_discount_or_copy" },
      { stage: "ENGINE", mechanic: "spell_chain" },
      { stage: "PAYOFF", mechanic: "token_or_damage_payoff" },
      { stage: "WIN", mechanic: "storm_or_burn" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "cheap_spells", targetMechanic: "spell_discount_or_copy", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "spell_discount_or_copy", targetMechanic: "spell_chain", relationship: "feeds" },
    ],
    commanderRoleWeights: { spell_copying: 0.95, cost_reduction: 0.7, copy_effects: 0.85 },
    commanderAxisKeys: ["ipv2_1_cmd_spells_stack_reliance", "ipv2_1_cmd_hand_resources_reliance"],
    commanderAxisWeights: [1, 0.6],
    requiredFunctions: ["spell_synergy", "payoff_spells"],
    supportingFunctions: ["card_draw", "protection"],
    catalogRoleBuckets: {
      enablers: ["spell_copying", "cost_reduction"],
      enginePieces: ["spell_copying", "card_draw"],
      payoffs: ["token_generation", "life_loss", "combat_payoff"],
      redundancy: ["spell_copying", "card_draw"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["countermagic", "removal"],
      finishers: ["life_loss", "token_generation"],
    },
    minCommanderDiscoverySupport: 0.4,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 12, interactionProtection: 10, finishers: 4 },
    winPlanSignals: ["spellslinger", "spell_chain"],
    structuralDemands: ["instants_sorceries", "draw", "interaction"],
    incidentalRoles: ["spell_copying", "token_generation"],
    incidentalMaxScore: 0.25,
    bracketIntentSignals: { comboDensity: 0.25, extraTurnDensity: 0.1, mldDensity: 0 },
  },
  {
    patternId: "artifact_value_engine",
    mechanicalName: "Artifact Synergy Engine",
    primaryAxes: ["artifacts", "activated_abilities"],
    secondaryAxes: ["mana_acceleration"],
    chain: [
      { stage: "INPUT", mechanic: "artifacts_on_board" },
      { stage: "ENABLER", mechanic: "artifact_ramp_or_draw" },
      { stage: "ENGINE", mechanic: "artifact_interactions" },
      { stage: "PAYOFF", mechanic: "value_or_combo" },
      { stage: "WIN", mechanic: "combo_or_grind" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "artifacts_on_board", targetMechanic: "artifact_ramp_or_draw", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "artifact_ramp_or_draw", targetMechanic: "artifact_interactions", relationship: "enables" },
    ],
    commanderRoleWeights: { ramp: 0.5, card_draw: 0.5, tutor: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_artifacts_reliance", "ipv2_1_cmd_activated_abilities_reliance"],
    commanderAxisWeights: [1, 0.7],
    requiredFunctions: ["artifact_synergy", "artifact_payoff"],
    supportingFunctions: ["ramp", "interaction"],
    catalogRoleBuckets: {
      enablers: ["ramp", "mana_generation"],
      enginePieces: ["tutor", "card_draw"],
      payoffs: ["combat_payoff", "card_advantage"],
      redundancy: ["ramp", "card_draw"],
      resourceSupport: ["ramp", "mana_generation"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["combat_payoff", "life_loss"],
    },
    minCommanderDiscoverySupport: 0.48,
    minCatalogCounts: { enablers: 10, enginePieces: 8, payoffs: 5, redundancy: 4, resourceSupport: 12, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["artifact_combo", "artifact_value"],
    structuralDemands: ["artifacts", "synergy_payoffs"],
    incidentalRoles: ["ramp"],
    incidentalMaxScore: 0.2,
    bracketIntentSignals: { comboDensity: 0.55, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "voltron_combat_engine",
    mechanicalName: "Commander Combat Engine",
    primaryAxes: ["creatures", "combat_payoff"],
    secondaryAxes: ["protection"],
    chain: [
      { stage: "INPUT", mechanic: "commander_on_board" },
      { stage: "ENABLER", mechanic: "equipment_auras" },
      { stage: "ENGINE", mechanic: "combat_enhancers" },
      { stage: "PAYOFF", mechanic: "commander_damage" },
      { stage: "WIN", mechanic: "lethal_commander" },
    ],
    mechanicEdges: [
      { sourceStage: "COMMANDER", targetStage: "ENABLER", sourceMechanic: "commander_on_board", targetMechanic: "equipment_auras", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "PAYOFF", sourceMechanic: "combat_enhancers", targetMechanic: "commander_damage", relationship: "converts" },
    ],
    commanderRoleWeights: { combat_payoff: 1, protection: 0.6, combat_manipulation: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance"],
    commanderAxisWeights: [0.8],
    requiredFunctions: ["combat_enhancement", "protection"],
    supportingFunctions: ["ramp", "removal"],
    catalogRoleBuckets: {
      enablers: ["combat_manipulation", "protection"],
      enginePieces: ["combat_payoff", "protection"],
      payoffs: ["combat_payoff"],
      redundancy: ["protection", "removal"],
      resourceSupport: ["ramp"],
      interactionProtection: ["removal", "protection", "board_wipe"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 8, enginePieces: 5, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 10, finishers: 3 },
    winPlanSignals: ["commander_damage", "voltron"],
    structuralDemands: ["enhancers", "protection", "ramp"],
    incidentalRoles: ["combat_payoff"],
    incidentalMaxScore: 0.22,
    bracketIntentSignals: { comboDensity: 0.05, extraTurnDensity: 0.05, mldDensity: 0 },
  },
  {
    patternId: "control_interaction_engine",
    mechanicalName: "Permission / Control Engine",
    primaryAxes: ["spells_stack", "hand_resources"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "mana_and_cards" },
      { stage: "ENABLER", mechanic: "card_draw" },
      { stage: "ENGINE", mechanic: "countermagic_and_removal" },
      { stage: "PAYOFF", mechanic: "value_or_lock" },
      { stage: "WIN", mechanic: "incremental_win" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "mana_and_cards", targetMechanic: "card_draw", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "card_draw", targetMechanic: "countermagic_and_removal", relationship: "feeds" },
    ],
    commanderRoleWeights: { countermagic: 1, removal: 0.7, card_draw: 0.6, board_wipe: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_spells_stack_reliance", "ipv2_1_cmd_hand_resources_reliance"],
    commanderAxisWeights: [0.9, 0.7],
    requiredFunctions: ["interaction", "card_advantage"],
    supportingFunctions: ["ramp", "finishers"],
    catalogRoleBuckets: {
      enablers: ["card_draw", "ramp"],
      enginePieces: ["countermagic", "removal", "board_wipe"],
      payoffs: ["card_advantage", "combat_payoff"],
      redundancy: ["countermagic", "removal"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["countermagic", "removal", "board_wipe"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.38,
    minCatalogCounts: { enablers: 8, enginePieces: 10, payoffs: 4, redundancy: 5, resourceSupport: 12, interactionProtection: 12, finishers: 3 },
    winPlanSignals: ["control", "permission"],
    structuralDemands: ["interaction_density", "draw"],
    incidentalRoles: ["removal", "countermagic"],
    incidentalMaxScore: 0.24,
    bracketIntentSignals: { comboDensity: 0.15, extraTurnDensity: 0.1, mldDensity: 0.1 },
  },
  {
    patternId: "combo_tutor_engine",
    mechanicalName: "Tutor Combo Assembly Engine",
    primaryAxes: ["library_search", "spells_stack"],
    secondaryAxes: ["activated_abilities"],
    chain: [
      { stage: "INPUT", mechanic: "mana_development" },
      { stage: "ENABLER", mechanic: "tutors" },
      { stage: "ENGINE", mechanic: "combo_pieces" },
      { stage: "PAYOFF", mechanic: "infinite_or_one_shot" },
      { stage: "WIN", mechanic: "deterministic_win" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "mana_development", targetMechanic: "tutors", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "tutors", targetMechanic: "combo_pieces", relationship: "feeds" },
    ],
    commanderRoleWeights: { tutor: 1, spell_copying: 0.5, cost_reduction: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_library_search_reliance", "ipv2_1_cmd_spells_stack_reliance"],
    commanderAxisWeights: [1, 0.6],
    requiredFunctions: ["tutors", "combo_assembly"],
    supportingFunctions: ["protection", "ramp"],
    catalogRoleBuckets: {
      enablers: ["tutor", "ramp"],
      enginePieces: ["tutor", "spell_copying", "cost_reduction"],
      payoffs: ["life_loss", "combat_payoff"],
      redundancy: ["tutor", "protection"],
      resourceSupport: ["ramp", "mana_generation"],
      interactionProtection: ["countermagic", "protection"],
      finishers: ["life_loss"],
    },
    minCommanderDiscoverySupport: 0.45,
    minCatalogCounts: { enablers: 8, enginePieces: 8, payoffs: 4, redundancy: 4, resourceSupport: 12, interactionProtection: 10, finishers: 3 },
    winPlanSignals: ["combo", "tutor_chain"],
    structuralDemands: ["tutors", "combo_pieces", "protection"],
    incidentalRoles: ["tutor"],
    incidentalMaxScore: 0.26,
    bracketIntentSignals: { comboDensity: 0.85, extraTurnDensity: 0.15, mldDensity: 0 },
  },
  {
    patternId: "enchantress_value_engine",
    mechanicalName: "Enchantment Value Engine",
    primaryAxes: ["enchantments", "hand_resources"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "enchantments" },
      { stage: "ENABLER", mechanic: "enchantress_draw" },
      { stage: "ENGINE", mechanic: "enchantment_synergy" },
      { stage: "PAYOFF", mechanic: "value_or_lock" },
      { stage: "WIN", mechanic: "incremental" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "enchantments", targetMechanic: "enchantress_draw", relationship: "feeds" },
    ],
    /** Enchantment-specific only — generic draw/recursion/value MUST NOT activate this pattern alone. */
    commanderRoleWeights: {},
    commanderAxisKeys: ["ipv2_1_cmd_enchantments_reliance"],
    commanderAxisWeights: [1],
    requiredFunctions: ["enchantment_density", "enchantment_payoff"],
    supportingFunctions: ["ramp", "removal"],
    catalogRoleBuckets: {
      enablers: ["card_draw", "ramp"],
      enginePieces: ["card_draw", "card_advantage"],
      payoffs: ["card_advantage", "life_gain"],
      redundancy: ["card_draw"],
      resourceSupport: ["ramp"],
      interactionProtection: ["removal", "board_wipe"],
      finishers: ["combat_payoff", "life_loss"],
    },
    minCommanderDiscoverySupport: 0.38,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["enchantress", "enchantment_value"],
    structuralDemands: ["enchantments", "enchantment_payoffs"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.1, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "landfall_ramp_engine",
    mechanicalName: "Land / Ramp Value Engine",
    primaryAxes: ["lands", "mana_acceleration"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "lands_in_play" },
      { stage: "ENABLER", mechanic: "land_ramp" },
      { stage: "ENGINE", mechanic: "landfall_triggers" },
      { stage: "PAYOFF", mechanic: "token_or_damage" },
      { stage: "WIN", mechanic: "combat_or_burn" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "lands_in_play", targetMechanic: "land_ramp", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "land_ramp", targetMechanic: "landfall_triggers", relationship: "enables" },
    ],
    commanderRoleWeights: { ramp: 1, mana_generation: 0.8, token_generation: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_mana_acceleration_reliance", "ipv2_1_cmd_lands_reliance"],
    commanderAxisWeights: [1, 0.7],
    requiredFunctions: ["land_synergy", "ramp"],
    supportingFunctions: ["removal", "card_draw"],
    catalogRoleBuckets: {
      enablers: ["ramp", "mana_generation"],
      enginePieces: ["ramp", "token_generation"],
      payoffs: ["combat_payoff", "life_loss", "token_generation"],
      redundancy: ["ramp"],
      resourceSupport: ["ramp", "mana_generation"],
      interactionProtection: ["removal", "board_wipe"],
      finishers: ["combat_payoff", "life_loss"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 12, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 15, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["landfall", "big_mana"],
    structuralDemands: ["lands", "ramp", "payoffs"],
    incidentalRoles: ["ramp"],
    incidentalMaxScore: 0.24,
    bracketIntentSignals: { comboDensity: 0.15, extraTurnDensity: 0, mldDensity: 0.2 },
  },
  {
    patternId: "etb_blink_value_engine",
    mechanicalName: "ETB / Blink Value Engine",
    primaryAxes: ["creatures", "triggered_abilities"],
    secondaryAxes: ["hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "creatures_with_etb" },
      { stage: "ENABLER", mechanic: "blink_flicker" },
      { stage: "ENGINE", mechanic: "etb_triggers" },
      { stage: "PAYOFF", mechanic: "value_conversion" },
      { stage: "WIN", mechanic: "incremental_advantage" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "creatures_with_etb", targetMechanic: "blink_flicker", relationship: "enables" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "blink_flicker", targetMechanic: "etb_triggers", relationship: "feeds" },
    ],
    commanderRoleWeights: { blink_flicker: 1, card_draw: 0.5, card_advantage: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance", "ipv2_1_cmd_triggered_abilities_reliance"],
    commanderAxisWeights: [0.8, 0.9],
    requiredFunctions: ["blink", "etb_value"],
    supportingFunctions: ["ramp", "protection"],
    catalogRoleBuckets: {
      enablers: ["blink_flicker", "ramp"],
      enginePieces: ["blink_flicker", "card_draw"],
      payoffs: ["card_advantage", "combat_payoff"],
      redundancy: ["blink_flicker"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.4,
    minCatalogCounts: { enablers: 6, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["blink", "etb_value"],
    structuralDemands: ["blink_enablers", "etb_creatures"],
    incidentalRoles: ["blink_flicker"],
    incidentalMaxScore: 0.24,
    bracketIntentSignals: { comboDensity: 0.2, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "exile_cast_engine",
    mechanicalName: "Exile / Cast-from-Exile Engine",
    primaryAxes: ["exile", "spells_stack"],
    secondaryAxes: ["hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "exiled_cards" },
      { stage: "ENABLER", mechanic: "exile_setup" },
      { stage: "ENGINE", mechanic: "cast_from_exile" },
      { stage: "PAYOFF", mechanic: "value_or_burst" },
      { stage: "WIN", mechanic: "resource_advantage" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "exiled_cards", targetMechanic: "exile_setup", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "exile_setup", targetMechanic: "cast_from_exile", relationship: "enables" },
    ],
    commanderRoleWeights: { cast_from_exile: 1, card_draw: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_exile_disruption", "ipv2_1_cmd_spells_stack_reliance"],
    commanderAxisWeights: [0.8, 0.6],
    requiredFunctions: ["exile_setup", "cast_from_exile"],
    supportingFunctions: ["ramp", "removal"],
    catalogRoleBuckets: {
      enablers: ["cast_from_exile", "ramp"],
      enginePieces: ["cast_from_exile", "card_draw"],
      payoffs: ["card_advantage", "combat_payoff", "life_loss"],
      redundancy: ["cast_from_exile"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["combat_payoff", "life_loss"],
    },
    minCommanderDiscoverySupport: 0.42,
    minCatalogCounts: { enablers: 6, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["exile_value", "impulse_cast"],
    structuralDemands: ["exile_enablers", "payoffs"],
    incidentalRoles: ["cast_from_exile"],
    incidentalMaxScore: 0.25,
    bracketIntentSignals: { comboDensity: 0.3, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "mill_library_engine",
    mechanicalName: "Library Mill Engine",
    primaryAxes: ["graveyard", "hand_resources"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "opponent_libraries" },
      { stage: "ENABLER", mechanic: "mill_effects" },
      { stage: "ENGINE", mechanic: "mill_acceleration" },
      { stage: "PAYOFF", mechanic: "mill_win_or_value" },
      { stage: "WIN", mechanic: "empty_library" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "opponent_libraries", targetMechanic: "mill_effects", relationship: "enables" },
    ],
    commanderRoleWeights: { mill: 1 },
    commanderAxisKeys: ["ipv2_1_cmd_graveyard_reliance"],
    commanderAxisWeights: [0.5],
    requiredFunctions: ["mill", "mill_payoff"],
    supportingFunctions: ["protection", "ramp"],
    catalogRoleBuckets: {
      enablers: ["mill"],
      enginePieces: ["mill", "card_draw"],
      payoffs: ["mill"],
      redundancy: ["mill"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["countermagic", "removal"],
      finishers: ["mill"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 8, enginePieces: 5, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["mill_out"],
    structuralDemands: ["mill_pieces", "protection"],
    incidentalRoles: ["mill", "graveyard_setup"],
    incidentalMaxScore: 0.28,
    bracketIntentSignals: { comboDensity: 0.1, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "group_slug_punisher_engine",
    mechanicalName: "Table-Wide Punisher Engine",
    primaryAxes: ["hand_resources", "creatures"],
    secondaryAxes: ["life_loss"],
    chain: [
      { stage: "INPUT", mechanic: "table_actions" },
      { stage: "ENABLER", mechanic: "punish_triggers" },
      { stage: "ENGINE", mechanic: "symmetrical_effects" },
      { stage: "PAYOFF", mechanic: "life_drain" },
      { stage: "WIN", mechanic: "opponent_elimination" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "table_actions", targetMechanic: "punish_triggers", relationship: "feeds" },
    ],
    commanderRoleWeights: { life_loss: 0.9, card_draw: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_hand_resources_reliance"],
    commanderAxisWeights: [0.7],
    requiredFunctions: ["punish", "drain"],
    supportingFunctions: ["protection", "ramp"],
    catalogRoleBuckets: {
      enablers: ["life_loss", "card_draw"],
      enginePieces: ["life_loss", "card_draw"],
      payoffs: ["life_loss"],
      redundancy: ["life_loss"],
      resourceSupport: ["ramp"],
      interactionProtection: ["removal", "board_wipe"],
      finishers: ["life_loss"],
    },
    minCommanderDiscoverySupport: 0.42,
    minCatalogCounts: { enablers: 6, enginePieces: 5, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["group_slug", "punisher"],
    structuralDemands: ["punish_pieces", "protection"],
    incidentalRoles: ["life_loss", "card_draw"],
    incidentalMaxScore: 0.24,
    bracketIntentSignals: { comboDensity: 0.05, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "counters_proliferate_engine",
    mechanicalName: "Counters / Proliferate Engine",
    primaryAxes: ["creatures", "activated_abilities"],
    secondaryAxes: ["hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "permanents_with_counters" },
      { stage: "ENABLER", mechanic: "counter_placement" },
      { stage: "ENGINE", mechanic: "proliferate_or_scale" },
      { stage: "PAYOFF", mechanic: "counter_payoff" },
      { stage: "WIN", mechanic: "combat_or_value" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "permanents_with_counters", targetMechanic: "counter_placement", relationship: "feeds" },
      { sourceStage: "ENABLER", targetStage: "ENGINE", sourceMechanic: "counter_placement", targetMechanic: "proliferate_or_scale", relationship: "enables" },
    ],
    commanderRoleWeights: { counter_synergy: 1, combat_payoff: 0.5, card_draw: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance", "ipv2_1_cmd_activated_abilities_reliance"],
    commanderAxisWeights: [0.8, 0.7],
    requiredFunctions: ["counter_placement", "counter_payoff"],
    supportingFunctions: ["protection", "ramp"],
    catalogRoleBuckets: {
      enablers: ["counter_synergy", "ramp"],
      enginePieces: ["counter_synergy", "combat_manipulation"],
      payoffs: ["combat_payoff", "card_draw"],
      redundancy: ["counter_synergy", "protection"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["counters", "proliferate"],
    structuralDemands: ["counter_enablers", "payoffs"],
    incidentalRoles: ["counter_synergy"],
    incidentalMaxScore: 0.24,
    bracketIntentSignals: { comboDensity: 0.15, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "stax_resource_denial_engine",
    mechanicalName: "Stax / Resource Denial Engine",
    primaryAxes: ["hand_resources", "artifacts"],
    secondaryAxes: ["spells_stack"],
    chain: [
      { stage: "INPUT", mechanic: "table_resources" },
      { stage: "ENABLER", mechanic: "tax_effects" },
      { stage: "ENGINE", mechanic: "resource_denial" },
      { stage: "PAYOFF", mechanic: "incremental_advantage" },
      { stage: "WIN", mechanic: "lock_then_win" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "table_resources", targetMechanic: "tax_effects", relationship: "feeds" },
    ],
    commanderRoleWeights: { countermagic: 0.6, removal: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_hand_resources_reliance", "ipv2_1_cmd_spells_stack_reliance"],
    commanderAxisWeights: [0.7, 0.6],
    requiredFunctions: ["taxes", "interaction"],
    supportingFunctions: ["card_draw", "finishers"],
    catalogRoleBuckets: {
      enablers: ["countermagic", "removal"],
      enginePieces: ["countermagic", "board_wipe"],
      payoffs: ["card_advantage"],
      redundancy: ["countermagic", "removal"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["countermagic", "removal", "board_wipe"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 8, enginePieces: 8, payoffs: 4, redundancy: 4, resourceSupport: 10, interactionProtection: 12, finishers: 3 },
    winPlanSignals: ["stax", "taxes"],
    structuralDemands: ["tax_pieces", "interaction"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.05, extraTurnDensity: 0.05, mldDensity: 0.05 },
  },
  {
    patternId: "aura_voltron_engine",
    mechanicalName: "Aura / Equipment Voltron Engine",
    primaryAxes: ["combat_payoff", "enchantments"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "auras_equipment" },
      { stage: "ENABLER", mechanic: "attach_or_cheat" },
      { stage: "ENGINE", mechanic: "combat_scaling" },
      { stage: "PAYOFF", mechanic: "commander_damage" },
      { stage: "WIN", mechanic: "combat" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "auras_equipment", targetMechanic: "attach_or_cheat", relationship: "enables" },
    ],
    commanderRoleWeights: { combat_manipulation: 1, combat_payoff: 0.85 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance", "ipv2_1_cmd_enchantments_reliance"],
    commanderAxisWeights: [0.9, 0.8],
    requiredFunctions: ["voltron", "protection"],
    supportingFunctions: ["ramp", "removal"],
    catalogRoleBuckets: {
      enablers: ["combat_manipulation", "protection"],
      enginePieces: ["combat_payoff", "combat_manipulation"],
      payoffs: ["combat_payoff"],
      redundancy: ["protection", "combat_manipulation"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.38,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["voltron", "aura_combat"],
    structuralDemands: ["auras", "equipment", "protection"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.1, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "treasure_sacrifice_engine",
    mechanicalName: "Treasure / Artifact Sacrifice Engine",
    primaryAxes: ["artifacts", "tokens"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "artifact_tokens" },
      { stage: "ENABLER", mechanic: "sacrifice_outlet" },
      { stage: "ENGINE", mechanic: "artifact_payoff" },
      { stage: "PAYOFF", mechanic: "value_or_damage" },
      { stage: "WIN", mechanic: "incremental" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "artifact_tokens", targetMechanic: "sacrifice_outlet", relationship: "feeds" },
    ],
    commanderRoleWeights: { sacrifice_outlet: 0.85, sacrifice_payoff: 1 },
    commanderAxisKeys: ["ipv2_1_cmd_artifacts_reliance", "ipv2_1_cmd_tokens_reliance"],
    commanderAxisWeights: [1, 0.7],
    requiredFunctions: ["artifact_sacrifice", "payoff"],
    supportingFunctions: ["ramp"],
    catalogRoleBuckets: {
      enablers: ["sacrifice_outlet", "token_generation"],
      enginePieces: ["sacrifice_payoff", "sacrifice_outlet"],
      payoffs: ["sacrifice_payoff", "card_draw"],
      redundancy: ["sacrifice_outlet"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal"],
      finishers: ["life_loss", "combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 5, redundancy: 4, resourceSupport: 10, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["treasure", "food", "aristocrats"],
    structuralDemands: ["outlets", "artifact_tokens"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.2, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "superfriends_engine",
    mechanicalName: "Planeswalker / Superfriends Engine",
    primaryAxes: ["planeswalkers", "counters"],
    secondaryAxes: ["hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "planeswalkers" },
      { stage: "ENABLER", mechanic: "proliferate" },
      { stage: "ENGINE", mechanic: "loyalty_engines" },
      { stage: "PAYOFF", mechanic: "ultimate_value" },
      { stage: "WIN", mechanic: "ultimate_or_grind" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "planeswalkers", targetMechanic: "proliferate", relationship: "feeds" },
    ],
    commanderRoleWeights: { counter_synergy: 1, card_draw: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_enchantments_reliance"],
    commanderAxisWeights: [0.6],
    requiredFunctions: ["proliferate", "planeswalker_support"],
    supportingFunctions: ["protection", "ramp"],
    catalogRoleBuckets: {
      enablers: ["ramp", "protection"],
      enginePieces: ["counter_synergy", "card_draw"],
      payoffs: ["card_advantage", "life_loss"],
      redundancy: ["protection"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["superfriends", "proliferate"],
    structuralDemands: ["planeswalkers", "proliferate"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.15, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "self_mill_graveyard_engine",
    mechanicalName: "Self-Mill / Graveyard Combo Engine",
    primaryAxes: ["graveyard", "recursion"],
    secondaryAxes: ["hand_resources"],
    chain: [
      { stage: "INPUT", mechanic: "self_mill" },
      { stage: "ENABLER", mechanic: "graveyard_setup" },
      { stage: "ENGINE", mechanic: "recursion_or_reanimate" },
      { stage: "PAYOFF", mechanic: "combo_or_value" },
      { stage: "WIN", mechanic: "engine_win" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "self_mill", targetMechanic: "graveyard_setup", relationship: "feeds" },
    ],
    commanderRoleWeights: { mill: 1, recursion: 0.9, reanimation: 0.85 },
    commanderAxisKeys: ["ipv2_1_cmd_graveyard_reliance", "ipv2_1_cmd_recursion_reliance"],
    commanderAxisWeights: [1, 0.85],
    requiredFunctions: ["mill", "recursion"],
    supportingFunctions: ["protection"],
    catalogRoleBuckets: {
      enablers: ["mill", "graveyard_setup"],
      enginePieces: ["recursion", "reanimation"],
      payoffs: ["card_advantage", "combat_payoff"],
      redundancy: ["recursion", "mill"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 4, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["self_mill", "graveyard_combo"],
    structuralDemands: ["mill", "recursion"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.45, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "legendary_tribal_engine",
    mechanicalName: "Legendary / Historic Engine",
    primaryAxes: ["creatures", "hand_resources"],
    secondaryAxes: ["artifacts"],
    chain: [
      { stage: "INPUT", mechanic: "legendary_permanents" },
      { stage: "ENABLER", mechanic: "legendary_synergy" },
      { stage: "ENGINE", mechanic: "legendary_value" },
      { stage: "PAYOFF", mechanic: "combat_or_combo" },
      { stage: "WIN", mechanic: "value_or_combat" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "legendary_permanents", targetMechanic: "legendary_synergy", relationship: "feeds" },
    ],
    commanderRoleWeights: { tutor: 0.85, combat_payoff: 0.6, card_draw: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance"],
    commanderAxisWeights: [0.8],
    requiredFunctions: ["legendary_synergy", "tutor"],
    supportingFunctions: ["ramp", "removal"],
    catalogRoleBuckets: {
      enablers: ["ramp", "tutor"],
      enginePieces: ["card_draw", "combat_payoff"],
      payoffs: ["combat_payoff", "card_advantage"],
      redundancy: ["tutor", "removal"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "protection"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 4 },
    winPlanSignals: ["legendary", "historic"],
    structuralDemands: ["legendary_density", "synergy"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.2, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "mana_ability_combo_engine",
    mechanicalName: "Mana-Ability Combo Engine",
    primaryAxes: ["mana_acceleration", "activated_abilities"],
    secondaryAxes: ["artifacts"],
    chain: [
      { stage: "INPUT", mechanic: "nonland_permanents" },
      { stage: "ENABLER", mechanic: "untap_or_copy" },
      { stage: "ENGINE", mechanic: "mana_ability_loop" },
      { stage: "PAYOFF", mechanic: "infinite_or_large_mana" },
      { stage: "WIN", mechanic: "combo" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "nonland_permanents", targetMechanic: "untap_or_copy", relationship: "enables" },
    ],
    commanderRoleWeights: { mana_generation: 1, ramp: 0.85 },
    commanderAxisKeys: ["ipv2_1_cmd_artifacts_reliance", "ipv2_1_cmd_lands_reliance"],
    commanderAxisWeights: [0.8, 0.5],
    requiredFunctions: ["mana_combo", "activated_abilities"],
    supportingFunctions: ["tutor"],
    catalogRoleBuckets: {
      enablers: ["ramp", "mana_generation"],
      enginePieces: ["mana_generation", "ramp"],
      payoffs: ["card_draw", "combat_payoff"],
      redundancy: ["ramp"],
      resourceSupport: ["ramp", "mana_generation"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.28,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 12, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["mana_combo"],
    structuralDemands: ["mana_rocks", "combo_pieces"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.55, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "exile_impulse_engine",
    mechanicalName: "Exile / Impulse Cast Engine",
    primaryAxes: ["hand_resources", "spells_stack"],
    secondaryAxes: ["artifacts"],
    chain: [
      { stage: "INPUT", mechanic: "exiled_cards" },
      { stage: "ENABLER", mechanic: "impulse_exile" },
      { stage: "ENGINE", mechanic: "cast_from_exile" },
      { stage: "PAYOFF", mechanic: "value_or_combo" },
      { stage: "WIN", mechanic: "value" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "exiled_cards", targetMechanic: "impulse_exile", relationship: "feeds" },
    ],
    commanderRoleWeights: { cast_from_exile: 1, card_draw: 0.5, spell_copying: 0.6 },
    commanderAxisKeys: ["ipv2_1_cmd_spells_stack_reliance", "ipv2_1_cmd_hand_resources_reliance"],
    commanderAxisWeights: [0.85, 0.7],
    requiredFunctions: ["cast_from_exile", "impulse"],
    supportingFunctions: ["ramp"],
    catalogRoleBuckets: {
      enablers: ["cast_from_exile", "card_draw"],
      enginePieces: ["cast_from_exile", "spell_copying"],
      payoffs: ["card_advantage", "combat_payoff"],
      redundancy: ["cast_from_exile"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["combat_payoff", "life_loss"],
    },
    minCommanderDiscoverySupport: 0.35,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 8, finishers: 3 },
    winPlanSignals: ["impulse", "exile_cast"],
    structuralDemands: ["impulse", "exile_payoffs"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.25, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "ninja_tempo_engine",
    mechanicalName: "Ninja Tempo / Topdeck Combat Engine",
    primaryAxes: ["combat_payoff", "spells_stack"],
    secondaryAxes: ["creatures"],
    chain: [
      { stage: "INPUT", mechanic: "evasive_attackers" },
      { stage: "ENABLER", mechanic: "ninjutsu_or_topdeck" },
      { stage: "ENGINE", mechanic: "combat_triggers" },
      { stage: "PAYOFF", mechanic: "life_loss_or_value" },
      { stage: "WIN", mechanic: "combat" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "evasive_attackers", targetMechanic: "ninjutsu_or_topdeck", relationship: "enables" },
    ],
    commanderRoleWeights: { combat_payoff: 1, combat_manipulation: 0.9, card_draw: 0.5 },
    commanderAxisKeys: ["ipv2_1_cmd_creatures_reliance", "ipv2_1_cmd_spells_stack_reliance"],
    commanderAxisWeights: [0.9, 0.6],
    requiredFunctions: ["ninjutsu", "combat_payoff"],
    supportingFunctions: ["removal", "countermagic"],
    catalogRoleBuckets: {
      enablers: ["combat_manipulation", "removal"],
      enginePieces: ["combat_payoff", "card_draw"],
      payoffs: ["life_loss", "combat_payoff"],
      redundancy: ["removal"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "countermagic"],
      finishers: ["life_loss", "combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.38,
    minCatalogCounts: { enablers: 8, enginePieces: 6, payoffs: 4, redundancy: 3, resourceSupport: 10, interactionProtection: 10, finishers: 4 },
    winPlanSignals: ["ninja", "tempo"],
    structuralDemands: ["evasive_creatures", "ninjutsu"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.15, extraTurnDensity: 0, mldDensity: 0 },
  },
  {
    patternId: "goodstuff_value_engine",
    mechanicalName: "Broad Value / Good-Stuff Engine",
    primaryAxes: ["hand_resources", "creatures"],
    secondaryAxes: ["artifacts", "enchantments"],
    chain: [
      { stage: "INPUT", mechanic: "quality_permanents" },
      { stage: "ENABLER", mechanic: "ramp_and_draw" },
      { stage: "ENGINE", mechanic: "value_permanents" },
      { stage: "PAYOFF", mechanic: "incremental_advantage" },
      { stage: "WIN", mechanic: "battlecruiser" },
    ],
    mechanicEdges: [
      { sourceStage: "INPUT", targetStage: "ENABLER", sourceMechanic: "quality_permanents", targetMechanic: "ramp_and_draw", relationship: "enables" },
    ],
    commanderRoleWeights: { card_draw: 0.6, ramp: 0.5, removal: 0.4 },
    commanderAxisKeys: ["ipv2_1_cmd_hand_resources_reliance", "ipv2_1_cmd_creatures_reliance"],
    commanderAxisWeights: [0.6, 0.5],
    requiredFunctions: ["value", "interaction"],
    supportingFunctions: ["ramp"],
    catalogRoleBuckets: {
      enablers: ["ramp", "card_draw"],
      enginePieces: ["card_draw", "removal"],
      payoffs: ["combat_payoff", "card_advantage"],
      redundancy: ["removal", "card_draw"],
      resourceSupport: ["ramp", "card_draw"],
      interactionProtection: ["removal", "board_wipe", "countermagic"],
      finishers: ["combat_payoff"],
    },
    minCommanderDiscoverySupport: 0.55,
    minCatalogCounts: { enablers: 10, enginePieces: 8, payoffs: 5, redundancy: 5, resourceSupport: 15, interactionProtection: 12, finishers: 4 },
    winPlanSignals: ["value", "goodstuff"],
    structuralDemands: ["efficient_spells", "mana_base", "interaction"],
    incidentalRoles: [],
    incidentalMaxScore: 0,
    bracketIntentSignals: { comboDensity: 0.1, extraTurnDensity: 0, mldDensity: 0 },
  },
];

const ARCHETYPE_KIND_OVERRIDES: Partial<Record<string, ArchetypeKind>> = {
  goodstuff_value_engine: "GENERIC_VALUE_FALLBACK",
};

function attachArchetypeKind(pattern: Omit<EnginePatternDef, "archetypeKind">): EnginePatternDef {
  return {
    ...pattern,
    archetypeKind: ARCHETYPE_KIND_OVERRIDES[pattern.patternId] ?? "MECHANICAL_ENGINE",
  };
}

export const MECHANICAL_ENGINE_PATTERNS_V1: EnginePatternDef[] =
  RAW_MECHANICAL_ENGINE_PATTERNS_V1.map(attachArchetypeKind);

export function enginePatternById(patternId: string): EnginePatternDef | undefined {
  return MECHANICAL_ENGINE_PATTERNS_V1.find((p) => p.patternId === patternId);
}
